INSERT INTO restaurants (name, area, city, cuisine, avg_rating, total_votes, avg_cost_for_two, restaurant_type, online_order) VALUES
('Jalsa', 'Banashankari', 'Bangalore', 'North Indian', 4.1, 775, 800, 'Casual Dining', TRUE),
('Spice Elephant', 'Banashankari', 'Bangalore', 'Chinese', 4.1, 787, 800, 'Casual Dining', TRUE),
('San Churro Cafe', 'Banashankari', 'Bangalore', 'Cafe', 3.8, 918, 800, 'Cafe', TRUE),
('Addhuri Udupi Bhojana', 'Banashankari', 'Bangalore', 'South Indian', 3.7, 88, 300, 'Quick Bites', FALSE),
('Grand Village', 'Basavanagudi', 'Bangalore', 'North Indian', 3.8, 166, 600, 'Casual Dining', FALSE),
('Timepass Dinner', 'Basavanagudi', 'Bangalore', 'North Indian', 3.8, 286, 600, 'Casual Dining', TRUE),
('Rosewood International Hotel - Bar & Restaurant', 'Mysore Road', 'Bangalore', 'North Indian', 3.6, 8, 800, 'Casual Dining', FALSE),
('Onesta', 'Banashankari', 'Bangalore', 'Pizza', 4.6, 2556, 600, 'Casual Dining', TRUE),
('Penthouse Cafe', 'Banashankari', 'Bangalore', 'Cafe', 4.0, 324, 700, 'Cafe', TRUE),
('Smacznego', 'Banashankari', 'Bangalore', 'Cafe', 4.2, 504, 550, 'Cafe', TRUE),
('CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The Alley', 'Banashankari', 'Bangalore', 'Cafe', 4.1, 402, 500, 'Cafe', TRUE),
('Cafe Shuffle', 'Banashankari', 'Bangalore', 'Cafe', 4.2, 150, 600, 'Cafe', TRUE),
('The Coffee Shack', 'Banashankari', 'Bangalore', 'Cafe', 4.2, 164, 500, 'Cafe', TRUE),
('Caf-Eleven', 'Banashankari', 'Bangalore', 'Cafe', 4.0, 424, 450, 'Cafe', FALSE),
('San Churro Cafe', 'Banashankari', 'Bangalore', 'Cafe', 3.8, 918, 800, 'Cafe', TRUE),
('Cafe Vivacity', 'Banashankari', 'Bangalore', 'Cafe', 3.8, 90, 650, 'Cafe', TRUE),
('Catch-up-ino', 'Banashankari', 'Bangalore', 'Cafe', 3.9, 133, 800, 'Cafe', TRUE),
('Kirthi''s Biryani', 'Banashankari', 'Bangalore', 'Chinese', 3.8, 144, 700, 'Cafe', TRUE),
('T3H Cafe', 'Banashankari', 'Bangalore', 'Cafe', 3.9, 93, 300, 'Cafe', FALSE),
('360 Atoms Restaurant And Cafe', 'Banashankari', 'Bangalore', 'Cafe', 3.1, 13, 400, 'Cafe', TRUE),
('The Vintage Cafe', 'Banashankari', 'Bangalore', 'Cafe', 3.0, 62, 400, 'Cafe', TRUE),
('Woodee Pizza', 'Banashankari', 'Bangalore', 'Cafe', 3.7, 180, 500, 'Cafe', TRUE),
('Cafe Coffee Day', 'Banashankari', 'Bangalore', 'Cafe', 3.6, 28, 900, 'Cafe', FALSE),
('My Tea House', 'Banashankari', 'Bangalore', 'Italian', 3.6, 62, 600, 'Quick Bites', TRUE),
('Hide Out Cafe', 'Banashankari', 'Bangalore', 'Cafe', 3.7, 31, 300, 'Cafe', FALSE),
('CAFE NOVA', 'Banashankari', 'Bangalore', 'Cafe', 3.2, 11, 600, 'Cafe', FALSE),
('Coffee Tindi', 'Banashankari', 'Bangalore', 'Cafe', 3.8, 75, 200, 'Cafe', TRUE),
('Sea Green Cafe', 'Banashankari', 'Bangalore', 'Cafe', 3.3, 4, 500, 'Cafe', FALSE),
('Cuppa', 'Banashankari', 'Bangalore', 'Cafe', 3.3, 23, 550, 'Cafe', FALSE),
('Srinathji''s Cafe', 'Basavanagudi', 'Bangalore', 'North Indian', 3.8, 148, 550, 'Casual Dining', FALSE),
('Redberrys', 'Basavanagudi', 'Bangalore', 'Cafe', 4.0, 219, 600, 'Cafe', TRUE),
('Foodiction', 'Banashankari', 'Bangalore', 'North Indian', 2.8, 506, 500, 'Quick Bites', TRUE),
('Sweet Truth', 'Banashankari', 'Bangalore', 'Bakery', 3.9, 35, 500, 'Delivery', TRUE),
('Ovenstory Pizza', 'Banashankari', 'Bangalore', 'Pizza', 3.9, 172, 750, 'Delivery', TRUE),
('Faasos', 'Banashankari', 'Bangalore', 'North Indian', 4.2, 415, 500, 'Quick Bites', TRUE),
('Behrouz Biryani', 'Banashankari', 'Bangalore', 'Biryani', 3.9, 230, 650, 'Delivery', TRUE),
('Fast And Fresh', 'Banashankari', 'Bangalore', 'North Indian', 2.8, 91, 400, 'Quick Bites', TRUE),
('Szechuan Dragon', 'Banashankari', 'Bangalore', 'Chinese', 4.2, 1647, 600, 'Casual Dining', TRUE),
('Empire Restaurant', 'Jayanagar', 'Bangalore', 'North Indian', 4.4, 4884, 750, 'Casual Dining', TRUE),
('Maruthi Davangere Benne Dosa', 'Banashankari', 'Bangalore', 'South Indian', 4.0, 17, 150, 'Quick Bites', TRUE),
('Chaatimes', 'Basavanagudi', 'Bangalore', 'Street Food', 3.8, 133, 200, 'Quick Bites', TRUE),
('Havyaka Mess', 'Banashankari', 'Bangalore', 'South Indian', 3.9, 28, 300, 'Mess', FALSE),
('McDonald''s', 'Banashankari', 'Bangalore', 'Burger', 3.9, 286, 500, 'Quick Bites', TRUE),
('Domino''s Pizza', 'Banashankari', 'Bangalore', 'Pizza', 3.9, 540, 800, 'Quick Bites', TRUE),
('Onesta', 'Banashankari', 'Bangalore', 'Pizza', 4.6, 2556, 600, 'Casual Dining', TRUE),
('Hotboxit', 'Banashankari', 'Bangalore', 'North Indian', 3.8, 36, 400, 'Delivery', FALSE),
('Kitchen Garden', 'Kumaraswamy Layout', 'Bangalore', 'North Indian', 3.6, 244, 300, 'Quick Bites', TRUE),
('Recipe', 'Kumaraswamy Layout', 'Bangalore', 'North Indian', 4.0, 804, 450, 'Casual Dining', TRUE),
('Beijing Bites', 'Rajarajeshwari Nagar', 'Bangalore', 'Chinese', 3.7, 679, 850, 'Casual Dining', TRUE),
('Tasty Bytes', 'Kumaraswamy Layout', 'Bangalore', 'North Indian', 3.1, 245, 300, 'Quick Bites', TRUE),
('Petoo', 'Banashankari', 'Bangalore', 'North Indian', 3.7, 21, 450, 'Quick Bites', FALSE),
('Shree Cool Point', 'Vijay Nagar', 'Bangalore', 'Fast Food', 4.1, 28, 150, 'Quick Bites', TRUE),
('Corner House Ice Cream', 'Banashankari', 'Bangalore', 'Ice Cream', 4.3, 345, 400, 'Dessert Parlor', FALSE),
('Biryanis And More', 'Jayanagar', 'Bangalore', 'Biryani', 4.0, 618, 750, 'Casual Dining', TRUE),
('Roving Feast', 'Banashankari', 'Bangalore', 'Italian', 4.0, 1047, 450, 'Quick Bites', FALSE),
('FreshMenu', 'Banashankari', 'Bangalore', 'Healthy Food', 3.9, 627, 450, 'Delivery', TRUE),
('Banashankari Donne Biriyani', 'Banashankari', 'Bangalore', 'Biryani', 3.8, 104, 300, 'Quick Bites', TRUE),
('Wamama', 'Banashankari', 'Bangalore', 'Asian', 4.2, 354, 800, 'Casual Dining', TRUE),
('Five Star Chicken', 'Banashankari', 'Bangalore', 'Fast Food', 3.6, 55, 200, 'Quick Bites', FALSE),
('XO Belgian Waffle', 'Banashankari', 'Bangalore', 'Desserts', 3.7, 17, 400, 'Dessert Parlor', TRUE),
('Peppy Peppers', 'Banashankari', 'Bangalore', 'Italian', 4.2, 244, 800, 'Casual Dining', FALSE),
('Goa 0 Km', 'Kumaraswamy Layout', 'Bangalore', 'Goan', 3.6, 163, 800, 'Casual Dining', TRUE),
('Chinese Kitchen', 'Basavanagudi', 'Bangalore', 'Chinese', 3.8, 58, 150, 'Quick Bites', TRUE),
('1947', 'Banashankari', 'Bangalore', 'North Indian', 4.0, 808, 850, 'Casual Dining', FALSE),
('Cake of the Day', 'Banashankari', 'Bangalore', 'Bakery', 3.7, 78, 150, 'Bakery', FALSE),
('Kabab Magic', 'Basavanagudi', 'Bangalore', 'North Indian', 4.1, 1720, 400, 'Quick Bites', TRUE),
('Namma Brahmin''s Idli', 'Jayanagar', 'Bangalore', 'South Indian', 3.6, 34, 100, 'Quick Bites', TRUE),
('Gustoes Beer House', 'Banashankari', 'Bangalore', 'Continental', 4.1, 868, 1200, 'Pub', FALSE),
('Sugar Rush', 'Banashankari', 'Bangalore', 'Bakery', 3.8, 39, 300, 'Bakery', FALSE),
('Burger King', 'Basavanagudi', 'Bangalore', 'Burger', 3.2, 71, 600, 'Quick Bites', TRUE),
('The Good Bowl', 'Banashankari', 'Bangalore', 'Italian', 3.6, 6, 500, 'Takeaway', TRUE),
('The Biryani Cafe', 'Banashankari', 'Bangalore', 'Biryani', 4.1, 520, 300, 'Quick Bites', FALSE),
('LSD Cafe', 'Banashankari', 'Bangalore', 'Chinese', 2.9, 84, 700, 'Delivery', FALSE),
('Rolls On Wheels', 'Banashankari', 'Bangalore', 'Fast Food', 3.6, 299, 300, 'Quick Bites', FALSE),
('Sri Guru Kottureshwara Davangere Benne Dosa', 'Basavanagudi', 'Bangalore', 'South Indian', 4.1, 558, 150, 'Quick Bites', TRUE),
('Devanna Dum Biriyani Centre', 'Banashankari', 'Bangalore', 'Biryani', 3.6, 28, 300, 'Quick Bites', TRUE),
('Kolbeh', 'Banashankari', 'Bangalore', 'Fast Food', 3.7, 22, 500, 'Quick Bites', FALSE),
('Upahar Sagar', 'Banashankari', 'Bangalore', 'South Indian', 3.8, 39, 350, 'Quick Bites', FALSE),
('Kadalu Sea Food Restaurant', 'Vijay Nagar', 'Bangalore', 'Seafood', 3.8, 153, 500, 'Fine Dining', TRUE),
('Frozen Bottle', 'Banashankari', 'Bangalore', 'Beverages', 4.2, 146, 400, 'Beverage Shop', TRUE),
('Parimala Sweets', 'Banashankari', 'Bangalore', 'Mithai', 3.5, 14, 200, 'Sweet Shop', FALSE),
('Vaishali Deluxe', 'Banashankari', 'Bangalore', 'North Indian', 3.8, 42, 700, 'Casual Dining', FALSE),
('The Big O Bakes', 'Banashankari', 'Bangalore', 'Bakery', 4.0, 66, 300, 'Bakery', FALSE),
('Meghana Foods', 'Jayanagar', 'Bangalore', 'Biryani', 4.4, 4401, 600, 'Casual Dining', TRUE),
('Krishna Sagar', 'Banashankari', 'Bangalore', 'North Indian', 3.5, 31, 200, 'Quick Bites', FALSE),
('Dessert Rose', 'Banashankari', 'Bangalore', 'Desserts', 3.5, 7, 500, 'Dessert Parlor', FALSE),
('Chickpet Donne Biryani House', 'Banashankari', 'Bangalore', 'Biryani', 3.7, 21, 250, 'Quick Bites', FALSE),
('Thanco''s Natural Ice Creams', 'Banashankari', 'Bangalore', 'Ice Cream', 3.2, 9, 300, 'Dessert Parlor', FALSE),
('Nandhini Deluxe', 'Banashankari', 'Bangalore', 'North Indian', 2.6, 283, 600, 'Casual Dining', FALSE),
('Vi Ra''s Bar and Restaurant', 'Banashankari', 'Bangalore', 'South Indian', 3.3, 62, 800, 'Bar', FALSE),
('Kaggis', 'Banashankari', 'Bangalore', 'Fast Food', 3.8, 64, 250, 'Quick Bites', FALSE),
('Ayda Persian Kitchen', 'Banashankari', 'Bangalore', 'North Indian', 3.7, 39, 950, 'Casual Dining', FALSE),
('Chatar Patar', 'Banashankari', 'Bangalore', 'Fast Food', 3.7, 65, 300, 'Quick Bites', FALSE),
('Polar Bear', 'Basavanagudi', 'Bangalore', 'Ice Cream', 3.8, 71, 400, 'Dessert Parlor', TRUE),
('Kidambi''s Kitchen', 'Banashankari', 'Bangalore', 'South Indian', 3.5, 52, 300, 'Quick Bites', FALSE),
('Mane Thindi', 'Banashankari', 'Bangalore', 'South Indian', 3.7, 130, 200, 'Quick Bites', FALSE),
('Kotian Karavali Restaurant', 'Banashankari', 'Bangalore', 'South Indian', 3.5, 10, 300, 'Quick Bites', FALSE),
('Floured-Baked With Love', 'Banashankari', 'Bangalore', 'Bakery', 3.8, 45, 400, 'Takeaway', FALSE),
('CAFE NOVA', 'Banashankari', 'Bangalore', 'Cafe', 3.2, 11, 600, 'Cafe', FALSE),
('Cakes & Slices', 'Banashankari', 'Bangalore', 'Bakery', 3.5, 13, 300, 'Bakery', FALSE),
('Spice 9', 'Banashankari', 'Bangalore', 'Biryani', 3.4, 8, 300, 'Quick Bites', FALSE),
('Naveen Kabab & Biriyani Mane', 'Banashankari', 'Bangalore', 'Biryani', 3.2, 9, 300, 'Quick Bites', FALSE),
('Katriguppe Donne Biryani', 'Banashankari', 'Bangalore', 'North Indian', 3.2, 4, 300, 'Quick Bites', FALSE),
('Atithi Point Ande Ka Funda', 'Banashankari', 'Bangalore', 'North Indian', 3.1, 29, 150, 'Quick Bites', FALSE),
('Just Bake', 'Banashankari', 'Bangalore', 'Bakery', 3.4, 8, 400, 'Bakery', FALSE),
('K27 - The Pub', 'Banashankari', 'Bangalore', 'Chinese', 3.1, 30, 1000, 'Bar', FALSE),
('Bengaluru Coffee House', 'Banashankari', 'Bangalore', 'South Indian', 4.1, 201, 300, 'Quick Bites', TRUE),
('New Mangalore Lunch Home', 'Banashankari', 'Bangalore', 'Mangalorean', 3.3, 7, 200, 'Quick Bites', FALSE),
('Coffee Bytes', 'Banashankari', 'Bangalore', 'Fast Food', 3.1, 6, 100, 'Quick Bites', FALSE),
('Parjanya Chat Zone', 'Banashankari', 'Bangalore', 'Street Food', 3.3, 17, 200, 'Quick Bites', FALSE),
('Kwality Wall''s Swirl''s Happiness Station', 'Banashankari', 'Bangalore', 'Ice Cream', 2.9, 25, 200, 'Dessert Parlor', FALSE),
('Ruchi Maayaka', 'Banashankari', 'Bangalore', 'South Indian', 3.3, 8, 100, 'Delivery', FALSE),
('Anna Kuteera', 'Banashankari', 'Bangalore', 'South Indian', 4.0, 771, 450, 'Casual Dining', TRUE),
('Darbar', 'Banashankari', 'Bangalore', 'North Indian', 3.0, 98, 800, 'Bar', FALSE),
('Vijayalakshmi', 'Basavanagudi', 'Bangalore', 'South Indian', 3.9, 47, 200, 'Quick Bites', TRUE),
('Sri Udupi Food Hub', 'Jayanagar', 'Bangalore', 'South Indian', 4.1, 175, 500, 'Casual Dining', TRUE),
('Udupi Upahar', 'Banashankari', 'Bangalore', 'South Indian', 3.8, 58, 300, 'Quick Bites', TRUE),
('House Of Kebabs', 'Basavanagudi', 'Bangalore', 'North Indian', 3.8, 540, 650, 'Casual Dining', TRUE),
('Roll N Rock', 'Kumaraswamy Layout', 'Bangalore', 'Chinese', 3.8, 124, 400, 'Quick Bites', TRUE),
('BOX8- Desi Meals', 'Banashankari', 'Bangalore', 'North Indian', 4.1, 340, 500, 'Takeaway', TRUE),
('KFC', 'Banashankari', 'Bangalore', 'Burger', 3.8, 505, 450, 'Quick Bites', TRUE),
('Roll Over', 'Jayanagar', 'Bangalore', 'Desserts', 4.1, 438, 500, 'Dessert Parlor', TRUE),
('Imperial Restaurant', 'Mysore Road', 'Bangalore', 'North Indian', 3.7, 264, 750, 'Casual Dining', TRUE),
('Lassi Shop', 'Kumaraswamy Layout', 'Bangalore', 'Beverages', 3.9, 169, 150, 'Beverage Shop', TRUE),
('The Fortuna', 'Kumaraswamy Layout', 'Bangalore', 'North Indian', 3.0, 67, 250, 'Quick Bites', TRUE),
('Wahab', 'Jayanagar', 'Bangalore', 'North Indian', 3.7, 97, 350, 'Quick Bites', TRUE),
('Al Diwan Biryanis And More', 'Basavanagudi', 'Bangalore', 'Biryani', 3.3, 12, 300, 'Takeaway', TRUE),
('New Gowda''s Fried Chicken', 'Banashankari', 'Bangalore', 'Biryani', 3.3, 12, 300, 'Quick Bites', TRUE),
('Canton', 'Jayanagar', 'Bangalore', 'Chinese', 3.6, 195, 800, 'Casual Dining', TRUE),
('Diabetics Dezire Sugarless Sweets and Bakes', 'Basavanagudi', 'Bangalore', 'Desserts', 3.3, 13, 300, 'Dessert Parlor', TRUE),
('The Blue Wagon - Kitchen', 'Jayanagar', 'Bangalore', 'Cafe', 4.6, 228, 400, 'Cafe', TRUE),
('HOT COFFEE', 'Basavanagudi', 'Bangalore', 'South Indian', 4.1, 70, 150, 'Quick Bites', TRUE),
('Patio 805', 'Jayanagar', 'Bangalore', 'Thai', 4.1, 364, 1200, 'Casual Dining', TRUE),
('Lassi Corner', 'Basavanagudi', 'Bangalore', 'Beverages', 3.7, 107, 150, 'Beverage Shop', TRUE),
('Sagar Deluxe', 'Kumaraswamy Layout', 'Bangalore', 'South Indian', 3.2, 167, 300, 'Quick Bites', TRUE),
('Kanti Sweets', 'Banashankari', 'Bangalore', 'Mithai', 4.0, 115, 400, 'Sweet Shop', TRUE),
('Vegetalia', 'Banashankari', 'Bangalore', 'Italian', 3.7, 27, 400, 'Takeaway', TRUE),
('Aramane Donne Biryani', 'Banashankari', 'Bangalore', 'Biryani', 3.5, 57, 200, 'Quick Bites', TRUE),
('Ande Ka Funda', 'Banashankari', 'Bangalore', 'North Indian', 3.8, 120, 250, 'Quick Bites', TRUE),
('Cake Ghar', 'Basavanagudi', 'Bangalore', 'Bakery', 3.8, 15, 400, 'Bakery', TRUE),
('Energy Addaa', 'Basavanagudi', 'Bangalore', 'Salad', 4.2, 64, 500, 'Quick Bites', TRUE),
('Bhattara Bhojana', 'Banashankari', 'Bangalore', 'South Indian', 3.6, 66, 150, 'Quick Bites', TRUE),
('Tandoori Knight', 'Banashankari', 'Bangalore', 'North Indian', 3.0, 290, 450, 'Quick Bites', TRUE),
('Dev Sagar - Food Street', 'Basavanagudi', 'Bangalore', 'Street Food', 4.1, 233, 200, 'Quick Bites', TRUE),
('Mitraa Da Pizza', 'Kumaraswamy Layout', 'Bangalore', 'Fast Food', 3.8, 115, 250, 'Quick Bites', TRUE),
('Paradise Premium', 'Banashankari', 'Bangalore', 'Biryani', 3.1, 119, 700, 'Casual Dining', TRUE),
('Grazers', 'Jayanagar', 'Bangalore', 'Cafe', 3.9, 291, 650, 'Cafe', TRUE),
('Shakes Theory', 'Jayanagar', 'Bangalore', 'Beverages', 4.5, 155, 300, 'Beverage Shop', TRUE),
('@Italy', 'Kumaraswamy Layout', 'Bangalore', 'Italian', 4.1, 305, 700, 'Casual Dining', TRUE),
('Chilli Flakes', 'Banashankari', 'Bangalore', 'Fast Food', 3.6, 46, 500, 'Quick Bites', TRUE),
('Calcutta Cafe', 'Kumaraswamy Layout', 'Bangalore', 'Bengali', 3.5, 45, 350, 'Quick Bites', TRUE),
('Old Mumbai Ice Cream', 'Banashankari', 'Bangalore', 'Ice Cream', 3.9, 38, 150, 'Dessert Parlor', TRUE),
('Donne Biriyani House', 'Banashankari', 'Bangalore', 'South Indian', 3.9, 441, 400, 'Quick Bites', TRUE),
('By 2 Coffee', 'Basavanagudi', 'Bangalore', 'South Indian', 3.9, 25, 100, 'Quick Bites', TRUE),
('Kedia''s Fun Food', 'Jayanagar', 'Bangalore', 'North Indian', 4.3, 630, 200, 'Quick Bites', TRUE),
('Davangere Butter Dosa Hotel', 'Kumaraswamy Layout', 'Bangalore', 'South Indian', 3.8, 25, 150, 'Quick Bites', TRUE),
('Just Shawarma', 'Kumaraswamy Layout', 'Bangalore', 'Arabian', 3.9, 160, 300, 'Quick Bites', TRUE),
('Mini Punjabi Dhaba', 'Banashankari', 'Bangalore', 'North Indian', 4.2, 287, 350, 'Quick Bites', TRUE),
('Mulabagilu Dosa', 'Basavanagudi', 'Bangalore', 'South Indian', 3.6, 11, 100, 'Quick Bites', TRUE),
('CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The Alley', 'Banashankari', 'Bangalore', 'Cafe', 4.1, 402, 500, 'Cafe', TRUE),
('Gokul Veg', 'Basavanagudi', 'Bangalore', 'North Indian', 3.8, 469, 750, 'Casual Dining', TRUE),
('Olive - Era', 'Kumaraswamy Layout', 'Bangalore', 'BBQ', 3.3, 511, 550, 'Casual Dining', TRUE),
('Udupi Ruchi', 'Banashankari', 'Bangalore', 'South Indian', 3.9, 57, 200, 'Quick Bites', TRUE),
('Madhappa Hindu Military Hotel', 'Banashankari', 'Bangalore', 'South Indian', 3.4, 14, 300, 'Quick Bites', TRUE),
('Gama Gama', 'Banashankari', 'Bangalore', 'South Indian', 3.9, 264, 200, 'Quick Bites', TRUE),
('The Vintage Cafe', 'Banashankari', 'Bangalore', 'Cafe', 3.0, 62, 400, 'Cafe', TRUE),
('Pizza Hut', 'Banashankari', 'Bangalore', 'Pizza', 3.8, 693, 750, 'Casual Dining', TRUE),
('Mangalore Pearl', 'Jayanagar', 'Bangalore', 'Mangalorean', 3.8, 242, 650, 'Casual Dining', TRUE),
('Asha Sweets Centre', 'Basavanagudi', 'Bangalore', 'Fast Food', 3.6, 27, 250, 'Dessert Parlor', TRUE),
('Twiststick House', 'Basavanagudi', 'Bangalore', 'Continental', 4.1, 163, 500, 'Quick Bites', TRUE),
('Cool Corner', 'Basavanagudi', 'Bangalore', 'Street Food', 4.2, 191, 250, 'Quick Bites', TRUE),
('Pizza Mane', 'Banashankari', 'Bangalore', 'Pizza', 3.5, 32, 150, 'Quick Bites', TRUE),
('Dal Tadkaa', 'Banashankari', 'Bangalore', 'North Indian', 2.5, 247, 500, 'Casual Dining', TRUE),
('Chutney Chang', 'Jayanagar', 'Bangalore', 'North Indian', 4.1, 2339, 1500, 'Casual Dining', TRUE),
('Mystique Palate', 'Jayanagar', 'Bangalore', 'Chinese', 4.1, 337, 300, 'Quick Bites', TRUE),
('Thamboola', 'Banashankari', 'Bangalore', 'North Indian', 3.9, 135, 800, 'Casual Dining', TRUE),
('Castle Rock', 'Uttarahalli', 'Bangalore', 'North Indian', 3.6, 172, 700, 'Casual Dining', TRUE),
('Vietnamese Kitchen', 'Banashankari', 'Bangalore', 'Vietnamese', 3.6, 105, 700, 'Casual Dining', TRUE),
('Smacznego', 'Banashankari', 'Bangalore', 'Cafe', 4.2, 504, 550, 'Cafe', TRUE),
('C Corner', 'Kumaraswamy Layout', 'Bangalore', 'Fast Food', 3.2, 36, 200, 'Quick Bites', TRUE),
('Paratha Merchant', 'Kumaraswamy Layout', 'Bangalore', 'North Indian', 3.1, 39, 300, 'Quick Bites', TRUE),
('North Rasoe', 'Kumaraswamy Layout', 'Bangalore', 'North Indian', 3.1, 5, 500, 'Casual Dining', TRUE),
('Toscano', 'Jayanagar', 'Bangalore', 'Italian', 4.3, 1129, 1300, 'Casual Dining', TRUE),
('Lord Of The Kitchen', 'Kumaraswamy Layout', 'Bangalore', 'North Indian', 3.9, 56, 350, 'Quick Bites', TRUE),
('Stoned Monkey', 'Banashankari', 'Bangalore', 'Desserts', 4.3, 860, 500, 'Dessert Parlor', TRUE),
('Central Jail Restaurant', 'Jayanagar', 'Bangalore', 'Andhra', 3.8, 412, 700, 'Casual Dining', TRUE),
('Bella', 'Jayanagar', 'Bangalore', 'Mangalorean', 3.9, 142, 1000, 'Casual Dining', TRUE),
('Vennela Andhra Meals', 'Jayanagar', 'Bangalore', 'Andhra', 3.0, 23, 400, 'Quick Bites', TRUE),
('New Prashanth Hotel', 'Jayanagar', 'Bangalore', 'South Indian', 3.6, 143, 750, 'Casual Dining', TRUE),
('The Grillo', 'Jayanagar', 'Bangalore', 'South Indian', 2.8, 80, 500, 'Casual Dining', TRUE),
('Re Malnad Nati Style Hotel', 'JP Nagar', 'Bangalore', 'South Indian', 3.6, 16, 400, 'Casual Dining', TRUE),
('Karma Kaapi', 'Jayanagar', 'Bangalore', 'Beverages', 4.4, 181, 250, 'Beverage Shop', TRUE),
('Tiwari''s', 'Jayanagar', 'Bangalore', 'North Indian', 3.8, 70, 200, 'Quick Bites', TRUE),
('Pizza Stop', 'Basavanagudi', 'Bangalore', 'Pizza', 3.8, 164, 600, 'Quick Bites', TRUE),
('Biggies Burger ''n'' More', 'Kumaraswamy Layout', 'Bangalore', 'Cafe', 3.6, 58, 650, 'Quick Bites', TRUE),
('Srinathji''s Cafe', 'Basavanagudi', 'Bangalore', 'North Indian', 3.8, 148, 550, 'Casual Dining', FALSE),
('Kollapuri''s', 'Basavanagudi', 'Bangalore', 'South Indian', 3.9, 206, 450, 'Quick Bites', FALSE),
('Kadamba Classic', 'Mysore Road', 'Bangalore', 'South Indian', 3.6, 16, 300, 'Quick Bites', FALSE),
('RS Shiv Sagar', 'Basavanagudi', 'Bangalore', 'North Indian', 3.7, 217, 450, 'Casual Dining', FALSE),
('Kholi Mane', 'Basavanagudi', 'Bangalore', 'Andhra', 3.6, 46, 450, 'Quick Bites', FALSE),
('Harshi Super Sandwich', 'Basavanagudi', 'Bangalore', 'Fast Food', 3.8, 148, 150, 'Quick Bites', FALSE),
('Cake Yard', 'Basavanagudi', 'Bangalore', 'Desserts', 3.4, 30, 250, 'Dessert Parlor', FALSE),
('Rosewood International Hotel - Bar & Restaurant', 'Mysore Road', 'Bangalore', 'North Indian', 3.6, 8, 800, 'Casual Dining', FALSE),
('Sri Udupi Veg', 'Jayanagar', 'Bangalore', 'South Indian', 3.3, 4, 250, 'Quick Bites', FALSE),
('Cake Art', 'Basavanagudi', 'Bangalore', 'Bakery', 3.5, 15, 400, 'Bakery', FALSE),
('Potato House', 'Uttarahalli', 'Bangalore', 'Street Food', 3.4, 9, 200, 'Quick Bites', TRUE),
('Matru Sagar', 'Mysore Road', 'Bangalore', 'South Indian', 3.7, 31, 300, 'Quick Bites', TRUE),
('Ugadi', 'Jayanagar', 'Bangalore', 'North Indian', 2.9, 177, 700, 'Casual Dining', TRUE),
('Sri Krishna Sweets', 'Basavanagudi', 'Bangalore', 'Mithai', 3.7, 22, 250, 'Sweet Shop', TRUE),
('In Time Cane Juice', 'Kumaraswamy Layout', 'Bangalore', 'Juices', 3.5, 10, 100, 'Beverage Shop', TRUE),
('Subway', 'Banashankari', 'Bangalore', 'Salad', 3.7, 136, 600, 'Quick Bites', TRUE),
('Daal Roti', 'Kumaraswamy Layout', 'Bangalore', 'North Indian', 2.9, 35, 250, 'Quick Bites', TRUE),
('The Lassi Park', 'Jayanagar', 'Bangalore', 'Juices', 4.1, 185, 200, 'Quick Bites', TRUE),
('Cafe Coffee Day', 'Jayanagar', 'Bangalore', 'Cafe', 3.2, 17, 900, 'Cafe', TRUE),
('A2B - Adyar Ananda Bhavan', 'Mysore Road', 'Bangalore', 'South Indian', 3.8, 155, 400, 'Casual Dining', TRUE),
('Srikrishna Bhavan', 'Banashankari', 'Bangalore', 'South Indian', 3.8, 42, 300, 'Quick Bites', TRUE),
('Timepass Dinner', 'Basavanagudi', 'Bangalore', 'North Indian', 3.8, 286, 600, 'Casual Dining', TRUE),
('Green Gardenia', 'Banashankari', 'Bangalore', 'North Indian', 3.8, 160, 700, 'Casual Dining', TRUE),
('J Spice', 'Banashankari', 'Bangalore', 'North Indian', 3.8, 59, 750, 'Casual Dining', TRUE),
('Karavali Family Restaurant', 'Jayanagar', 'Bangalore', 'Seafood', 3.5, 90, 500, 'Casual Dining', TRUE),
('Karavali Lunch Home', 'Kumaraswamy Layout', 'Bangalore', 'South Indian', 3.7, 51, 350, 'Quick Bites', TRUE),
('Hatti Kaapi', 'Jayanagar', 'Bangalore', 'South Indian', 4.0, 89, 200, 'Quick Bites', TRUE),
('Kolkata Kathi Roll''s', 'Banashankari', 'Bangalore', 'Fast Food', 3.6, 18, 250, 'Quick Bites', TRUE),
('Upahara Darshini', 'Basavanagudi', 'Bangalore', 'North Indian', 3.9, 40, 600, 'Casual Dining', TRUE),
('The Chaat Shop', 'Basavanagudi', 'Bangalore', 'Fast Food', 2.5, 35, 200, 'Quick Bites', TRUE),
('Anda Ka Funda', 'Jayanagar', 'Bangalore', 'North Indian', 3.4, 89, 250, 'Quick Bites', TRUE),
('Shri Vinayaka Ice N Juice', 'Basavanagudi', 'Bangalore', 'Beverages', 3.2, 11, 150, 'Quick Bites', TRUE),
('My Tea House', 'Banashankari', 'Bangalore', 'Italian', 3.6, 62, 600, 'Quick Bites', TRUE),
('Ibaco', 'Jayanagar', 'Bangalore', 'Desserts', 3.9, 33, 300, 'Dessert Parlor', TRUE),
('Jalaram Sweets', 'Jayanagar', 'Bangalore', 'Desserts', 3.8, 32, 250, 'Sweet Shop', TRUE),
('Samskruti - Sanman Gardenia', 'Jayanagar', 'Bangalore', 'North Indian', 4.1, 139, 550, 'Casual Dining', TRUE),
('Bendakaluru Bytes', 'Vijay Nagar', 'Bangalore', 'Fast Food', 3.2, 154, 300, 'Quick Bites', TRUE),
('Cocoa Bakes', 'Banashankari', 'Bangalore', 'Bakery', 3.6, 14, 350, 'Bakery', TRUE),
('Chumma Delicious', 'Banashankari', 'Bangalore', 'South Indian', 3.7, 237, 200, 'Quick Bites', TRUE),
('New Prashanth Hotel', 'Banashankari', 'Bangalore', 'Biryani', 3.9, 388, 650, 'Casual Dining', TRUE),
('Dwaraka Grand', 'Kumaraswamy Layout', 'Bangalore', 'South Indian', 3.9, 128, 500, 'Casual Dining', TRUE),
('Gufha - The President Hotel', 'Jayanagar', 'Bangalore', 'North Indian', 4.1, 1875, 1200, 'Casual Dining', TRUE),
('Cafe Vivacity', 'Banashankari', 'Bangalore', 'Cafe', 3.8, 90, 650, 'Cafe', TRUE),
('Tanna''s Kitchen', 'Kumaraswamy Layout', 'Bangalore', 'Italian', 3.1, 7, 250, 'Quick Bites', TRUE),
('Shree Mandarathi Grand', 'Uttarahalli', 'Bangalore', 'South Indian', 3.7, 38, 400, 'Casual Dining', TRUE),
('Mojo Pizza - 2X Toppings', 'Banashankari', 'Bangalore', 'Pizza', 4.2, 179, 600, 'Delivery', TRUE),
('Iceberg Icecreams', 'Basavanagudi', 'Bangalore', 'Desserts', 4.0, 43, 250, 'Dessert Parlor', TRUE),
('South Kitchen', 'Basavanagudi', 'Bangalore', 'South Indian', 4.3, 275, 100, 'Quick Bites', TRUE),
('Chung Wah', 'Jayanagar', 'Bangalore', 'Chinese', 3.7, 323, 850, 'Casual Dining', TRUE),
('Shanthi Sagar', 'Uttarahalli', 'Bangalore', 'South Indian', 3.1, 28, 400, 'Casual Dining', TRUE),
('Millet Mama', 'Basavanagudi', 'Bangalore', 'South Indian', 3.9, 18, 200, 'Quick Bites', TRUE),
('Bangarpet Chat Express', 'Basavanagudi', 'Bangalore', 'Street Food', 3.3, 6, 100, 'Quick Bites', TRUE),
('Prems Graama Bhojanam', 'Jayanagar', 'Bangalore', 'South Indian', 4.3, 322, 400, 'Casual Dining', TRUE),
('Java City', 'Jayanagar', 'Bangalore', 'Cafe', 2.6, 157, 450, 'Cafe', TRUE),
('Kamat Bugle Rock', 'Basavanagudi', 'Bangalore', 'South Indian', 3.9, 543, 300, 'Quick Bites', TRUE),
('Woodee Pizza', 'Banashankari', 'Bangalore', 'Cafe', 3.7, 180, 500, 'Cafe', TRUE),
('Puliyogare Point', 'Basavanagudi', 'Bangalore', 'South Indian', 4.2, 444, 100, 'Quick Bites', TRUE),
('Bangalore Agarwal Bhavan', 'Jayanagar', 'Bangalore', 'Street Food', 3.9, 134, 400, 'Quick Bites', TRUE),
('Rustic Stove', 'Jayanagar', 'Bangalore', 'North Indian', 3.8, 577, 900, 'Casual Dining', TRUE),
('Udupi Ruchi Grand', 'Banashankari', 'Bangalore', 'South Indian', 4.2, 60, 200, 'Quick Bites', TRUE),
('De Thaali', 'Jayanagar', 'Bangalore', 'North Indian', 3.9, 144, 550, 'Casual Dining', TRUE),
('Spice Elephant', 'Banashankari', 'Bangalore', 'Chinese', 4.1, 787, 800, 'Casual Dining', TRUE),
('Just Thindi', 'Basavanagudi', 'Bangalore', 'South Indian', 3.6, 16, 200, 'Quick Bites', TRUE),
('Matru Sagar', 'Banashankari', 'Bangalore', 'South Indian', 3.6, 84, 250, 'Quick Bites', TRUE),
('Vasanth Vihar - Since 1965', 'Banashankari', 'Bangalore', 'South Indian', 3.6, 95, 150, 'Quick Bites', TRUE),
('Sea Spice by 7 Star', 'Banashankari', 'Bangalore', 'Seafood', 4.0, 349, 1200, 'Casual Dining', TRUE),
('Desi Dawat', 'Kumaraswamy Layout', 'Bangalore', 'North Indian', 3.7, 248, 400, 'Quick Bites', TRUE),
('Cafe Aira', 'Basavanagudi', 'Bangalore', 'Cafe', 4.1, 216, 500, 'Cafe', TRUE),
('Penthouse Cafe', 'Banashankari', 'Bangalore', 'Cafe', 4.0, 324, 700, 'Cafe', TRUE),
('Mast Punjabi', 'Kumaraswamy Layout', 'Bangalore', 'North Indian', 2.6, 231, 400, 'Quick Bites', TRUE),
('South Grand', 'Uttarahalli', 'Bangalore', 'South Indian', 3.4, 102, 400, 'Casual Dining', TRUE),
('Catch-up-ino', 'Banashankari', 'Bangalore', 'Cafe', 3.9, 133, 800, 'Cafe', TRUE),
('The Pizzeria', 'Banashankari', 'Bangalore', 'Pizza', 2.8, 45, 800, 'Casual Dining', TRUE),
('Cafe Zone', 'Kumaraswamy Layout', 'Bangalore', 'Fast Food', 3.9, 149, 300, 'Quick Bites', TRUE),
('Ruchis Point', 'Banashankari', 'Bangalore', 'Fast Food', 3.8, 75, 200, 'Quick Bites', TRUE),
('Firangi Bake', 'Rajarajeshwari Nagar', 'Bangalore', 'Mexican', 4.0, 53, 600, 'Delivery', TRUE),
('The Royal Corner - Pai Viceroy', 'Jayanagar', 'Bangalore', 'North Indian', 4.2, 815, 900, 'Casual Dining', TRUE),
('Hara Fine Dine', 'Banashankari', 'Bangalore', 'North Indian', 4.0, 633, 800, 'Casual Dining', TRUE),
('Chocoberry', 'Jayanagar', 'Bangalore', 'Ice Cream', 3.5, 56, 400, 'Dessert Parlor', TRUE),
('Dakshin Grand', 'Banashankari', 'Bangalore', 'South Indian', 3.0, 82, 300, 'Quick Bites', TRUE),
('Sandwichwallas', 'Jayanagar', 'Bangalore', 'Fast Food', 3.7, 35, 200, 'Quick Bites', TRUE),
('Chai Mane', 'Basavanagudi', 'Bangalore', 'Juices', 3.6, 20, 150, 'Quick Bites', TRUE),
('SLV Upachar', 'Kumaraswamy Layout', 'Bangalore', 'South Indian', 3.1, 14, 250, 'Quick Bites', TRUE),
('Waffle-A-Go Go', 'Banashankari', 'Bangalore', 'Fast Food', 3.9, 70, 400, 'Dessert Parlor', TRUE),
('Cross Road Cafe', 'Jayanagar', 'Bangalore', 'Cafe', 3.9, 91, 300, 'Cafe', TRUE),
('Anand Donne Biriyani', 'Jayanagar', 'Bangalore', 'Biryani', 3.6, 45, 200, 'Quick Bites', TRUE),
('Seven Star', 'Banashankari', 'Bangalore', 'North Indian', 3.4, 7, 250, 'Quick Bites', TRUE),
('Stop ''N'' Joy', 'Banashankari', 'Bangalore', 'Fast Food', 3.8, 28, 150, 'Quick Bites', TRUE),
('Sri Yaksha Shiv Sagar', 'Banashankari', 'Bangalore', 'North Indian', 3.6, 24, 600, 'Casual Dining', TRUE),
('Fudge', 'Basavanagudi', 'Bangalore', 'Desserts', 3.8, 36, 200, 'Dessert Parlor', TRUE),
('Just Bunny', 'Jayanagar', 'Bangalore', 'Fast Food', 3.5, 11, 200, 'Quick Bites', TRUE),
('Bakers Town', 'Kumaraswamy Layout', 'Bangalore', 'Cafe', 3.8, 77, 650, 'Cafe', TRUE),
('Shree Mahalakshmi Sweets', 'Banashankari', 'Bangalore', 'Mithai', 3.2, 8, 100, 'Sweet Shop', TRUE),
('Kaapi Kendra', 'Jayanagar', 'Bangalore', 'South Indian', 3.7, 14, 100, 'Quick Bites', TRUE),
('Ivy', 'Kumaraswamy Layout', 'Bangalore', 'North Indian', 3.8, 210, 600, 'Casual Dining', TRUE),
('The Airos', 'Jayanagar', 'Bangalore', 'Cafe', 4.1, 130, 650, 'Cafe', TRUE),
('Chai Kraft', 'Jayanagar', 'Bangalore', 'Beverages', 4.1, 30, 100, 'Beverage Shop', TRUE),
('Kirthi''s Biryani', 'Banashankari', 'Bangalore', 'Chinese', 3.8, 144, 700, 'Cafe', TRUE),
('South Point Pub', 'Basavanagudi', 'Bangalore', 'North Indian', 3.4, 11, 800, 'Bar', TRUE),
('The Trundle', 'Jayanagar', 'Bangalore', 'Chinese', 3.7, 133, 700, 'Casual Dining', TRUE),
('The Krishna Grand Xpress', 'Jayanagar', 'Bangalore', 'South Indian', 4.0, 136, 350, 'Quick Bites', TRUE),
('Sri Krishna Darshini', 'Basavanagudi', 'Bangalore', 'South Indian', 3.1, 4, 200, 'Quick Bites', TRUE),
('Shringar Sweets & Snacks', 'Basavanagudi', 'Bangalore', 'Mithai', 3.5, 11, 200, 'Sweet Shop', TRUE),
('Udupi Grand', 'Basavanagudi', 'Bangalore', 'South Indian', 3.8, 74, 300, 'Quick Bites', TRUE),
('Ganesh Grand', 'Basavanagudi', 'Bangalore', 'South Indian', 3.7, 30, 300, 'Quick Bites', TRUE),
('Shreyas Upahar & Burger Point', 'Basavanagudi', 'Bangalore', 'South Indian', 3.0, 7, 200, 'Quick Bites', TRUE),
('Coffee Tindi', 'Banashankari', 'Bangalore', 'Cafe', 3.8, 75, 200, 'Cafe', TRUE),
('Little Cafe', 'Basavanagudi', 'Bangalore', 'Cafe', 3.7, 54, 600, 'Cafe', TRUE),
('Mumbai Badam Milk & Lassi Center', 'Basavanagudi', 'Bangalore', 'Beverages', 3.6, 23, 100, 'Kiosk', TRUE),
('Sri Krishna Sagar', 'Banashankari', 'Bangalore', 'North Indian', 3.2, 119, 400, 'Casual Dining', TRUE),
('Mylari Biryani Family Restaurant', 'Banashankari', 'Bangalore', 'Biryani', 3.7, 73, 400, 'Quick Bites', TRUE),
('1980s Games Cafe', 'Basavanagudi', 'Bangalore', 'Cafe', 3.4, 58, 400, 'Cafe', TRUE),
('Kadala Tarangaa', 'Banashankari', 'Bangalore', 'Mangalorean', 3.6, 129, 600, 'Casual Dining', TRUE),
('Namma Biryani', 'Banashankari', 'Bangalore', 'Biryani', 3.6, 24, 250, 'Quick Bites', TRUE),
('Nandhanu''s Rasoi', 'Kumaraswamy Layout', 'Bangalore', 'Chinese', 3.0, 175, 400, 'Quick Bites', TRUE),
('Hotel Pork Paradise', 'Mysore Road', 'Bangalore', 'South Indian', 3.7, 21, 300, 'Quick Bites', TRUE),
('As On Fire', 'South Bangalore', 'Bangalore', 'Pizza', 3.5, 41, 400, 'Food Truck', TRUE),
('J K Fish Land', 'Jayanagar', 'Bangalore', 'Seafood', 3.6, 35, 300, 'Quick Bites', TRUE),
('Curry Leaves', 'Basavanagudi', 'Bangalore', 'Andhra', 4.1, 176, 800, 'Casual Dining', TRUE),
('Lassi Shop', 'Banashankari', 'Bangalore', 'Beverages', 3.5, 45, 300, 'Beverage Shop', TRUE),
('Magic Meals', 'Jayanagar', 'Bangalore', 'Fast Food', 3.7, 47, 400, 'Quick Bites', TRUE),
('Desi Cream Junction', 'Jayanagar', 'Bangalore', 'Chinese', 3.7, 36, 650, 'Casual Dining', TRUE),
('Drunken Monkey', 'Kumaraswamy Layout', 'Bangalore', 'Beverages', 3.8, 52, 400, 'Beverage Shop', TRUE),
('Ruchi''s Corner', 'Banashankari', 'Bangalore', 'Fast Food', 2.7, 123, 200, 'Quick Bites', TRUE),
('Tandoori Bytes', 'Kumaraswamy Layout', 'Bangalore', 'North Indian', 3.6, 59, 700, 'Casual Dining', TRUE),
('Bangalore Donne Biriyani', 'Kumaraswamy Layout', 'Bangalore', 'South Indian', 3.2, 4, 300, 'Quick Bites', TRUE),
('SGS Non Veg - Gundu Pulav', 'Banashankari', 'Bangalore', 'Biryani', 3.8, 101, 400, 'Quick Bites', TRUE),
('Keventers', 'Banashankari', 'Bangalore', 'Desserts', 3.7, 54, 400, 'Beverage Shop', TRUE),
('Navi Food Point', 'Basavanagudi', 'Bangalore', 'Fast Food', 3.6, 22, 200, 'Quick Bites', TRUE),
('Shawarma Inc', 'Banashankari', 'Bangalore', 'Rolls', 3.1, 31, 250, 'Takeaway', TRUE),
('The Cafe Nuts and Bolts', 'Kumaraswamy Layout', 'Bangalore', 'Cafe', 3.0, 29, 500, 'Cafe', TRUE),
('AM WOW', 'Jayanagar', 'Bangalore', 'Beverages', 3.4, 6, 100, 'Beverage Shop', TRUE),
('Lalbagh Grand', 'Basavanagudi', 'Bangalore', 'South Indian', 3.0, 22, 250, 'Quick Bites', TRUE),
('Funjabi Curries', 'Banashankari', 'Bangalore', 'North Indian', 2.9, 11, 500, 'Quick Bites', TRUE),
('Eat Repeat', 'Basavanagudi', 'Bangalore', 'South Indian', 3.9, 101, 150, 'Quick Bites', TRUE),
('Salut', 'Jayanagar', 'Bangalore', 'Continental', 4.1, 442, 1200, 'Pub', TRUE),
('Nammura Donne Biriyani', 'Basavanagudi', 'Bangalore', 'Biryani', 3.5, 155, 400, 'Quick Bites', TRUE),
('Lassi Stop', 'Banashankari', 'Bangalore', 'Beverages', 3.4, 12, 150, 'Beverage Shop', TRUE),
('Dakshin Kitchen', 'Basavanagudi', 'Bangalore', 'South Indian', 3.6, 15, 100, 'Quick Bites', TRUE),
('Sri Sai Cafe', 'Basavanagudi', 'Bangalore', 'South Indian', 3.5, 10, 200, 'Quick Bites', TRUE),
('Sri Sai 99 Variety Dosa', 'Banashankari', 'Bangalore', 'South Indian', 3.8, 25, 300, 'Quick Bites', TRUE),
('Utsav Restaurant', 'Banashankari', 'Bangalore', 'North Indian', 3.8, 61, 300, 'Quick Bites', TRUE),
('Crunch and Munch', 'Uttarahalli', 'Bangalore', 'Chinese', 3.7, 23, 300, 'Quick Bites', TRUE),
('Food Geek', 'Basavanagudi', 'Bangalore', 'Sandwich', 3.8, 25, 350, 'Quick Bites', TRUE),
('Sri Krishna Aramane', 'Kumaraswamy Layout', 'Bangalore', 'South Indian', 3.7, 40, 200, 'Quick Bites', TRUE),
('Great Indian Rolls', 'Basavanagudi', 'Bangalore', 'Rolls', 3.3, 4, 100, 'Quick Bites', TRUE),
('Chats Point', 'Basavanagudi', 'Bangalore', 'Fast Food', 3.4, 8, 150, 'Quick Bites', TRUE),
('Food Point', 'Kumaraswamy Layout', 'Bangalore', 'North Indian', 3.5, 32, 300, 'Quick Bites', TRUE),
('Swarga Ruchi', 'Basavanagudi', 'Bangalore', 'South Indian', 3.3, 10, 200, 'Quick Bites', TRUE),
('Kolkata King', 'Basavanagudi', 'Bangalore', 'Fast Food', 3.4, 6, 300, 'Quick Bites', TRUE),
('Sandwich Mama''s And Frozen Monster', 'Jayanagar', 'Bangalore', 'Ice Cream', 3.8, 53, 250, 'Quick Bites', TRUE),
('New Rajadhani Spicy', 'Kumaraswamy Layout', 'Bangalore', 'North Indian', 3.7, 67, 700, 'Casual Dining', TRUE),
('Big Mishra Pedha', 'Jayanagar', 'Bangalore', 'Mithai', 2.9, 23, 250, 'Sweet Shop', TRUE),
('VEGeatz', 'Banashankari', 'Bangalore', 'South Indian', 3.4, 19, 200, 'Quick Bites', TRUE),
('Foodizo', 'Banashankari', 'Bangalore', 'Desserts', 3.6, 24, 300, 'Quick Bites', TRUE),
('Food Springs', 'Jayanagar', 'Bangalore', 'South Indian', 4.0, 232, 400, 'Quick Bites', TRUE),
('Chung''s Chinese Corner', 'Jayanagar', 'Bangalore', 'Chinese', 3.9, 221, 700, 'Casual Dining', TRUE),
('Eurasia Pasta and Barbeque by Little Italy', 'Jayanagar', 'Bangalore', 'Italian', 4.1, 1063, 1200, 'Casual Dining', TRUE),
('Goli Vada Pav No. 1', 'Basavanagudi', 'Bangalore', 'Street Food', 3.7, 93, 200, 'Quick Bites', TRUE),
('Ragoo''s', 'Jayanagar', 'Bangalore', 'Italian', 3.9, 233, 800, 'Casual Dining', TRUE),
('Pure & Natural', 'Jayanagar', 'Bangalore', 'Fast Food', 3.9, 211, 500, 'Casual Dining', TRUE),
('Maiyas', 'Jayanagar', 'Bangalore', 'North Indian', 4.0, 1778, 200, 'Quick Bites', TRUE),
('Sip n Dine', 'Vijay Nagar', 'Bangalore', 'North Indian', 3.6, 218, 800, 'Casual Dining', TRUE),
('Cafe Mondo', 'Basavanagudi', 'Bangalore', 'Cafe', 3.7, 514, 600, 'Cafe', TRUE),
('Jalpaan', 'Jayanagar', 'Bangalore', 'North Indian', 4.0, 866, 900, 'Casual Dining', TRUE),
('Kataria''s Pakwan', 'Kumaraswamy Layout', 'Bangalore', 'North Indian', 3.2, 96, 400, 'Quick Bites', TRUE),
('Juicy Momos', 'Banashankari', 'Bangalore', 'Tibetan', 3.5, 80, 250, 'Quick Bites', TRUE),
('Amande Patisserie', 'Basavanagudi', 'Bangalore', 'Bakery', 4.0, 73, 300, 'Bakery', TRUE),
('Anand Sweets and Savouries', 'Jayanagar', 'Bangalore', 'Mithai', 3.9, 84, 400, 'Sweet Shop', TRUE),
('Chicken Hunt', 'Banashankari', 'Bangalore', 'South Indian', 3.5, 88, 350, 'Quick Bites', TRUE),
('Swadesh Tadka', 'Banashankari', 'Bangalore', 'North Indian', 3.5, 179, 600, 'Casual Dining', TRUE),
('Cane-O-La', 'Basavanagudi', 'Bangalore', 'Juices', 3.8, 61, 100, 'Quick Bites', TRUE),
('New Biryani Mane', 'Uttarahalli', 'Bangalore', 'North Indian', 3.7, 128, 450, 'Casual Dining', TRUE),
('Upahara Darshini', 'Jayanagar', 'Bangalore', 'South Indian', 3.8, 339, 400, 'Quick Bites', TRUE),
('Karnataka Bhel House', 'Basavanagudi', 'Bangalore', 'Street Food', 4.1, 449, 100, 'Quick Bites', TRUE),
('Sreeraj Lassi Bar', 'Jayanagar', 'Bangalore', 'Beverages', 4.1, 210, 150, 'Dessert Parlor', TRUE),
('Juice Junction Food Court', 'Basavanagudi', 'Bangalore', 'Juices', 3.7, 57, 200, 'Quick Bites', TRUE),
('Bunt''s Biriyani Palace', 'Banashankari', 'Bangalore', 'North Indian', 3.0, 213, 400, 'Quick Bites', TRUE),
('Chai Point', 'Jayanagar', 'Bangalore', 'Tea', 3.2, 208, 250, 'Beverage Shop', TRUE),
('Janahaar', 'Banashankari', 'Bangalore', 'South Indian', 3.8, 70, 100, 'Quick Bites', TRUE),
('Redberrys', 'Basavanagudi', 'Bangalore', 'Cafe', 4.0, 219, 600, 'Cafe', TRUE),
('Utsav', 'Banashankari', 'Bangalore', 'North Indian', 3.7, 59, 200, 'Quick Bites', TRUE),
('Meat And Eat', 'Banashankari', 'Bangalore', 'Fast Food', 3.1, 10, 500, 'Quick Bites', TRUE),
('Snacks Bite', 'Kumaraswamy Layout', 'Bangalore', 'Fast Food', 3.0, 9, 400, 'Quick Bites', TRUE),
('The Spice Saga', 'Kumaraswamy Layout', 'Bangalore', 'Biryani', 3.7, 124, 750, 'Casual Dining', TRUE),
('Dakshin Cafe', 'Kumaraswamy Layout', 'Bangalore', 'South Indian', 3.7, 19, 100, 'Quick Bites', TRUE),
('Kaulige Millet Corner', 'Basavanagudi', 'Bangalore', 'Healthy Food', 3.3, 4, 150, 'Quick Bites', TRUE),
('Ifruit Ice Cream', 'Kumaraswamy Layout', 'Bangalore', 'Desserts', 3.3, 4, 150, 'Dessert Parlor', TRUE),
('Havmor', 'Basavanagudi', 'Bangalore', 'Ice Cream', 3.8, 21, 200, 'Dessert Parlor', TRUE),
('Grand Food', 'Banashankari', 'Bangalore', 'South Indian', 3.4, 8, 250, 'Quick Bites', TRUE),
('Dining Hut', 'Kumaraswamy Layout', 'Bangalore', 'North Indian', 3.5, 10, 400, 'Quick Bites', TRUE),
('Desi Swaad', 'Kumaraswamy Layout', 'Bangalore', 'North Indian', 3.5, 10, 400, 'Quick Bites', TRUE),
('Yummy Momos', 'Kumaraswamy Layout', 'Bangalore', 'Momos', 3.2, 4, 200, 'Quick Bites', TRUE),
('Masale Daan', 'Banashankari', 'Bangalore', 'North Indian', 3.1, 4, 350, 'Delivery', TRUE),
('Grow Fit', 'JP Nagar', 'Bangalore', 'Healthy Food', 3.6, 16, 500, 'Takeaway', TRUE),
('Lassi Spot', 'Kumaraswamy Layout', 'Bangalore', '', 3.3, 4, 100, 'Beverage Shop', TRUE),
('Sandwich Hub', 'Jayanagar', 'Bangalore', 'Fast Food', 3.4, 12, 300, 'Quick Bites', TRUE),
('Udupi Sri Krishna Cafe', 'Jayanagar', 'Bangalore', 'North Indian', 3.9, 14, 600, 'Casual Dining', TRUE),
('Starlite Bakery & Fastfood', 'Jayanagar', 'Bangalore', 'North Indian', 3.7, 0, 300, 'Quick Bites', TRUE),
('Veganbreak24x7', 'City Market', 'Bangalore', 'South Indian', 2.8, 5, 199, 'Takeaway', TRUE),
('Aadhya Hotel', 'Basavanagudi', 'Bangalore', 'South Indian', 3.3, 5, 800, 'Casual Dining', TRUE),
('Dodda Mane Baaduta', 'Banashankari', 'Bangalore', 'North Indian', 3.5, 15, 250, 'Quick Bites', TRUE),
('Swadd Kitchen', 'Basavanagudi', 'Bangalore', 'North Indian', 3.4, 4, 500, 'Casual Dining', TRUE),
('Happy Chopsticks', 'Basavanagudi', 'Bangalore', 'Chinese', 3.6, 17, 300, 'Quick Bites', TRUE),
('Udupi Upachar', 'Banashankari', 'Bangalore', 'South Indian', 3.3, 6, 500, 'Quick Bites', TRUE),
('Davanagere Benne Dose Hut', 'Banashankari', 'Bangalore', 'South Indian', 3.4, 10, 100, 'Quick Bites', TRUE),
('Jalsa', 'Banashankari', 'Bangalore', 'North Indian', 4.1, 775, 800, 'Casual Dining', TRUE),
('Subz', 'Jayanagar', 'Bangalore', 'North Indian', 4.2, 2022, 1000, 'Casual Dining', TRUE),
('Cafe Shuffle', 'Banashankari', 'Bangalore', 'Cafe', 4.2, 150, 600, 'Cafe', TRUE),
('Mint and Mustard', 'Basavanagudi', 'Bangalore', 'North Indian', 4.0, 232, 750, 'Casual Dining', TRUE),
('Chinese Square', 'Basavanagudi', 'Bangalore', 'Chinese', 3.9, 38, 200, 'Quick Bites', TRUE),
('Punjabi Raswada', 'Jayanagar', 'Bangalore', 'North Indian', 3.5, 431, 800, 'Casual Dining', TRUE),
('Vinny''s', 'Banashankari', 'Bangalore', 'Pizza', 4.2, 2115, 800, 'Casual Dining', TRUE),
('Chetty''s Corner', 'Uttarahalli', 'Bangalore', 'Fast Food', 3.4, 30, 200, 'Quick Bites', TRUE),
('Kapoor''s Cafe', 'Jayanagar', 'Bangalore', 'North Indian', 4.2, 150, 800, 'Casual Dining', TRUE),
('Donne Biryani & Kabab Corner', 'Kumaraswamy Layout', 'Bangalore', 'Chinese', 3.3, 12, 200, 'Quick Bites', TRUE),
('Sukh Sagar', 'Jayanagar', 'Bangalore', 'South Indian', 3.8, 155, 450, 'Casual Dining', TRUE),
('S M V Snacks Corner', 'Basavanagudi', 'Bangalore', 'Fast Food', 3.7, 33, 200, 'Quick Bites', TRUE),
('Andhra Ruchulu', 'Jayanagar', 'Bangalore', 'Andhra', 4.1, 666, 1000, 'Casual Dining', TRUE),
('Steaming Mugs', 'Basavanagudi', 'Bangalore', 'Cafe', 3.9, 240, 700, 'Cafe', TRUE),
('San Churro Cafe', 'Banashankari', 'Bangalore', 'Cafe', 3.8, 918, 800, 'Cafe', TRUE),
('Rajathadri Food Fort', 'Jayanagar', 'Bangalore', 'South Indian', 4.0, 465, 600, 'Casual Dining', TRUE),
('Brew Meister', 'Jayanagar', 'Bangalore', 'North Indian', 4.1, 970, 1500, 'Microbrewery', TRUE),
('Rasoi', 'Banashankari', 'Bangalore', 'North Indian', 3.3, 128, 300, 'Quick Bites', TRUE),
('Mr. Singh Da Dhaba', 'Kumaraswamy Layout', 'Bangalore', 'North Indian', 3.6, 241, 300, 'Quick Bites', TRUE),
('Kababs N Biryani', 'Banashankari', 'Bangalore', 'South Indian', 3.4, 22, 200, 'Quick Bites', TRUE),
('Ayodhya Upachar', 'Banashankari', 'Bangalore', 'South Indian', 4.3, 734, 200, 'Quick Bites', TRUE),
('Biriyani Mane', 'Jayanagar', 'Bangalore', 'North Indian', 3.8, 130, 400, 'Quick Bites', TRUE),
('Cafe Ajfan', 'Jayanagar', 'Bangalore', 'Cafe', 4.2, 261, 700, 'Cafe', TRUE),
('Brundhavana Food Point', 'Kumaraswamy Layout', 'Bangalore', 'South Indian', 4.0, 191, 300, 'Quick Bites', TRUE),
('SLV Corner Restaurant', 'Basavanagudi', 'Bangalore', 'South Indian', 4.1, 364, 550, 'Casual Dining', TRUE),
('Hotel New Karavali', 'Banashankari', 'Bangalore', 'Mangalorean', 3.8, 133, 300, 'Quick Bites', TRUE),
('The Krishna Grand', 'Banashankari', 'Bangalore', 'North Indian', 3.9, 888, 750, 'Casual Dining', TRUE),
('360 Atoms Restaurant And Cafe', 'Banashankari', 'Bangalore', 'Cafe', 3.1, 13, 400, 'Cafe', TRUE),
('Roti Ghar', 'Basavanagudi', 'Bangalore', 'North Indian', 3.9, 750, 500, 'Casual Dining', TRUE),
('The Coffee Shack', 'Banashankari', 'Bangalore', 'Cafe', 4.2, 164, 500, 'Cafe', TRUE),
('Kettle & Kegs', 'Banashankari', 'Bangalore', 'Tea', 3.2, 6, 200, 'Delivery', TRUE),
('Baisakhi', 'Basavanagudi', 'Bangalore', 'North Indian', 3.8, 527, 500, 'Casual Dining', TRUE),
('Corner House Ice Cream', 'Banashankari', 'Bangalore', 'Ice Cream', 4.3, 345, 400, 'Dessert Parlor', FALSE),
('Poonam Sweets', 'Banashankari', 'Bangalore', 'Mithai', 4.4, 356, 150, 'Sweet Shop', FALSE),
('XO Belgian Waffle', 'Banashankari', 'Bangalore', 'Desserts', 3.7, 17, 400, 'Dessert Parlor', TRUE),
('Old Mumbai Ice Cream', 'Banashankari', 'Bangalore', 'Ice Cream', 3.9, 38, 150, 'Dessert Parlor', TRUE),
('Cake of the Day', 'Banashankari', 'Bangalore', 'Bakery', 3.7, 78, 150, 'Bakery', FALSE),
('Amma''s Pastries', 'Banashankari', 'Bangalore', 'Bakery', 3.8, 60, 400, 'Dessert Parlor', FALSE),
('Kanti Sweets', 'Banashankari', 'Bangalore', 'Mithai', 4.0, 115, 400, 'Sweet Shop', TRUE),
('Sugar Rush', 'Banashankari', 'Bangalore', 'Bakery', 3.8, 39, 300, 'Bakery', FALSE),
('Polar Bear', 'Banashankari', 'Bangalore', 'Ice Cream', 3.9, 116, 400, 'Dessert Parlor', TRUE),
('San Churro Cafe', 'Banashankari', 'Bangalore', 'Cafe', 3.8, 918, 800, 'Cafe', TRUE),
('Anand Sweets and Savouries', 'Banashankari', 'Bangalore', 'Mithai', 3.7, 46, 400, 'Sweet Shop', FALSE),
('Ibaco', 'Banashankari', 'Bangalore', 'Desserts', 3.9, 41, 300, 'Dessert Parlor', TRUE),
('Kirthi''s Biryani', 'Banashankari', 'Bangalore', 'Chinese', 3.8, 144, 700, 'Cafe', TRUE),
('The Lassi and Juice Park', 'Banashankari', 'Bangalore', 'Juices', 3.8, 28, 150, 'Beverage Shop', FALSE),
('Stoned Monkey', 'Banashankari', 'Bangalore', 'Desserts', 4.3, 860, 500, 'Dessert Parlor', TRUE),
('Parimala Sweets', 'Banashankari', 'Bangalore', 'Mithai', 3.5, 14, 200, 'Sweet Shop', FALSE),
('The Big O Bakes', 'Banashankari', 'Bangalore', 'Bakery', 4.0, 66, 300, 'Bakery', FALSE),
('Shree Mahalakshmi Sweets', 'Banashankari', 'Bangalore', 'Mithai', 3.2, 8, 100, 'Sweet Shop', TRUE),
('Keventers', 'Banashankari', 'Bangalore', 'Desserts', 3.7, 54, 400, 'Beverage Shop', TRUE),
('Dessert Rose', 'Banashankari', 'Bangalore', 'Desserts', 3.5, 7, 500, 'Dessert Parlor', FALSE),
('Thanco''s Natural Ice Creams', 'Banashankari', 'Bangalore', 'Ice Cream', 3.2, 9, 300, 'Dessert Parlor', FALSE),
('Corner Stone', 'Banashankari', 'Bangalore', 'Beverages', 3.6, 42, 300, 'Beverage Shop', FALSE),
('Kaggis', 'Banashankari', 'Bangalore', 'Fast Food', 3.8, 64, 250, 'Quick Bites', FALSE),
('Cocoa Bakes', 'Banashankari', 'Bangalore', 'Bakery', 3.6, 14, 350, 'Bakery', TRUE),
('Floured-Baked With Love', 'Banashankari', 'Bangalore', 'Bakery', 3.8, 45, 400, 'Takeaway', FALSE),
('CAFE NOVA', 'Banashankari', 'Bangalore', 'Cafe', 3.2, 11, 600, 'Cafe', FALSE),
('Cakes & Slices', 'Banashankari', 'Bangalore', 'Bakery', 3.5, 13, 300, 'Bakery', FALSE),
('Arun Ice Cream', 'Banashankari', 'Bangalore', 'Ice Cream', 3.4, 7, 150, 'Dessert Parlor', FALSE),
('Just Bake', 'Banashankari', 'Bangalore', 'Bakery', 3.4, 8, 400, 'Bakery', FALSE),
('Kwality Wall''s Swirl''s Happiness Station', 'Banashankari', 'Bangalore', 'Ice Cream', 2.9, 25, 200, 'Dessert Parlor', FALSE),
('Sweet N Swirl', 'Banashankari', 'Bangalore', 'Desserts', 3.2, 17, 150, 'Dessert Parlor', FALSE),
('Sweet Truth', 'Banashankari', 'Bangalore', 'Bakery', 3.9, 35, 500, 'Delivery', TRUE),
('Waffle-A-Go Go', 'Banashankari', 'Bangalore', 'Fast Food', 3.9, 70, 400, 'Dessert Parlor', TRUE),
('Sri Venkateshwara Sweet Meat Stall', 'Basavanagudi', 'Bangalore', 'Mithai', 4.0, 98, 400, 'Sweet Shop', FALSE),
('Baskin Robbins', 'Basavanagudi', 'Bangalore', 'Ice Cream', 3.7, 25, 250, 'Dessert Parlor', FALSE),
('Redberrys', 'Basavanagudi', 'Bangalore', 'Cafe', 4.0, 219, 600, 'Cafe', TRUE),
('Amande Patisserie', 'Basavanagudi', 'Bangalore', 'Bakery', 4.0, 73, 300, 'Bakery', TRUE),
('Srinivasa Brahmins Bakery', 'Basavanagudi', 'Bangalore', 'Bakery', 3.6, 16, 150, 'Bakery', FALSE),
('Jain Bakes', 'Basavanagudi', 'Bangalore', 'Bakery', 3.6, 8, 250, 'Bakery', FALSE),
('Cake Ghar', 'Basavanagudi', 'Bangalore', 'Bakery', 3.8, 15, 400, 'Bakery', TRUE),
('KC Das - Sweet Spot', 'Basavanagudi', 'Bangalore', 'Mithai', 3.6, 46, 200, 'Sweet Shop', FALSE),
('Diabetics Dezire Sugarless Sweets and Bakes', 'Basavanagudi', 'Bangalore', 'Desserts', 3.3, 13, 300, 'Dessert Parlor', TRUE),
('Cake Yard', 'Basavanagudi', 'Bangalore', 'Desserts', 3.3, 9, 250, 'Dessert Parlor', TRUE),
('Iceberg Icecreams', 'Basavanagudi', 'Bangalore', 'Desserts', 4.0, 43, 250, 'Dessert Parlor', TRUE),
('A2B Veg - Adyar Ananda Bhavan', 'Basavanagudi', 'Bangalore', 'South Indian', 2.7, 97, 400, 'Casual Dining', TRUE),
('Sri Krishna Sweets', 'Basavanagudi', 'Bangalore', 'Mithai', 3.7, 22, 250, 'Sweet Shop', TRUE),
('Cake Art', 'Basavanagudi', 'Bangalore', 'Bakery', 3.5, 15, 400, 'Bakery', FALSE),
('Asha Sweets Centre', 'Basavanagudi', 'Bangalore', 'Fast Food', 3.6, 27, 250, 'Dessert Parlor', TRUE),
('The Krishna Grand', 'Banashankari', 'Bangalore', 'North Indian', 3.9, 888, 750, 'Casual Dining', TRUE),
('Sea Spice by 7 Star', 'Banashankari', 'Bangalore', 'Seafood', 4.0, 349, 1200, 'Casual Dining', TRUE),
('Mini Punjabi Dhaba', 'Banashankari', 'Bangalore', 'North Indian', 4.2, 287, 350, 'Quick Bites', TRUE),
('Onesta', 'Banashankari', 'Bangalore', 'Pizza', 4.6, 2556, 600, 'Casual Dining', TRUE),
('Wamama', 'Banashankari', 'Bangalore', 'Asian', 4.2, 354, 800, 'Casual Dining', TRUE),
('Jalsa', 'Banashankari', 'Bangalore', 'North Indian', 4.1, 775, 800, 'Casual Dining', TRUE),
('Vinny''s', 'Banashankari', 'Bangalore', 'Pizza', 4.2, 2115, 800, 'Casual Dining', TRUE),
('Jcubez', 'Banashankari', 'Bangalore', 'Finger Food', 3.8, 977, 1300, 'Lounge', FALSE),
('Gustoes Beer House', 'Banashankari', 'Bangalore', 'Continental', 4.1, 868, 1200, 'Pub', FALSE),
('Penthouse Cafe', 'Banashankari', 'Bangalore', 'Cafe', 4.0, 324, 700, 'Cafe', TRUE),
('Spice Elephant', 'Banashankari', 'Bangalore', 'Chinese', 4.1, 787, 800, 'Casual Dining', TRUE),
('Smacznego', 'Banashankari', 'Bangalore', 'Cafe', 4.2, 504, 550, 'Cafe', TRUE),
('CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The Alley', 'Banashankari', 'Bangalore', 'Cafe', 4.1, 402, 500, 'Cafe', TRUE),
('Cafe Shuffle', 'Banashankari', 'Bangalore', 'Cafe', 4.2, 150, 600, 'Cafe', TRUE),
('The Coffee Shack', 'Banashankari', 'Bangalore', 'Cafe', 4.2, 164, 500, 'Cafe', TRUE),
('Peppy Peppers', 'Banashankari', 'Bangalore', 'Italian', 4.2, 244, 800, 'Casual Dining', FALSE),
('Anna Kuteera', 'Banashankari', 'Bangalore', 'South Indian', 4.0, 771, 450, 'Casual Dining', TRUE),
('Szechuan Dragon', 'Banashankari', 'Bangalore', 'Chinese', 4.2, 1647, 600, 'Casual Dining', TRUE),
('1947', 'Banashankari', 'Bangalore', 'North Indian', 4.0, 808, 850, 'Casual Dining', FALSE),
('Caf-Eleven', 'Banashankari', 'Bangalore', 'Cafe', 4.0, 424, 450, 'Cafe', FALSE),
('Thamboola', 'Banashankari', 'Bangalore', 'North Indian', 3.9, 135, 800, 'Casual Dining', TRUE),
('Havyaka Mess', 'Banashankari', 'Bangalore', 'South Indian', 3.9, 28, 300, 'Mess', FALSE),
('San Churro Cafe', 'Banashankari', 'Bangalore', 'Cafe', 3.8, 918, 800, 'Cafe', TRUE),
('Cafe Vivacity', 'Banashankari', 'Bangalore', 'Cafe', 3.8, 90, 650, 'Cafe', TRUE),
('Chung Wah', 'Banashankari', 'Bangalore', 'Chinese', 3.9, 519, 900, 'Casual Dining', TRUE),
('Vietnamese Kitchen', 'Banashankari', 'Bangalore', 'Vietnamese', 3.6, 105, 700, 'Casual Dining', TRUE),
('Blue Wings Bar & Restaurant', 'Banashankari', 'Bangalore', 'North Indian', 3.7, 43, 700, 'Bar', FALSE),
('Anand Sweets and Savouries', 'Banashankari', 'Bangalore', 'Mithai', 3.7, 46, 400, 'Sweet Shop', FALSE),
('Catch-up-ino', 'Banashankari', 'Bangalore', 'Cafe', 3.9, 133, 800, 'Cafe', TRUE),
('Kirthi''s Biryani', 'Banashankari', 'Bangalore', 'Chinese', 3.8, 144, 700, 'Cafe', TRUE),
('T3H Cafe', 'Banashankari', 'Bangalore', 'Cafe', 3.9, 93, 300, 'Cafe', FALSE),
('Srikrishna Bhavan', 'Banashankari', 'Bangalore', 'South Indian', 3.8, 42, 300, 'Quick Bites', TRUE),
('Dal Tadkaa', 'Banashankari', 'Bangalore', 'North Indian', 2.5, 247, 500, 'Casual Dining', TRUE),
('360 Atoms Restaurant And Cafe', 'Banashankari', 'Bangalore', 'Cafe', 3.1, 13, 400, 'Cafe', TRUE),
('New Imperial Restaurant', 'Banashankari', 'Bangalore', 'North Indian', 3.7, 39, 450, 'Casual Dining', FALSE),
('The Vintage Cafe', 'Banashankari', 'Bangalore', 'Cafe', 3.0, 62, 400, 'Cafe', TRUE),
('Green Gardenia', 'Banashankari', 'Bangalore', 'North Indian', 3.8, 160, 700, 'Casual Dining', TRUE),
('Parimala Sweets', 'Banashankari', 'Bangalore', 'Mithai', 3.5, 14, 200, 'Sweet Shop', FALSE),
('Vaishali Deluxe', 'Banashankari', 'Bangalore', 'North Indian', 3.8, 42, 700, 'Casual Dining', FALSE),
('Paradise Premium', 'Banashankari', 'Bangalore', 'Biryani', 3.1, 119, 700, 'Casual Dining', TRUE),
('Kadala Tarangaa', 'Banashankari', 'Bangalore', 'Mangalorean', 3.6, 129, 600, 'Casual Dining', TRUE),
('Vi Ra''s Bar and Restaurant', 'Banashankari', 'Bangalore', 'South Indian', 3.3, 62, 800, 'Bar', FALSE),
('Sri Yaksha Shiv Sagar', 'Banashankari', 'Bangalore', 'North Indian', 3.6, 24, 600, 'Casual Dining', TRUE),
('Nandhini Deluxe', 'Banashankari', 'Bangalore', 'North Indian', 2.6, 283, 600, 'Casual Dining', FALSE),
('Corner Stone', 'Banashankari', 'Bangalore', 'Beverages', 3.6, 42, 300, 'Beverage Shop', FALSE),
('Karavali Fish Center', 'Banashankari', 'Bangalore', 'Mangalorean', 3.4, 10, 300, 'Quick Bites', FALSE),
('Ayda Persian Kitchen', 'Banashankari', 'Bangalore', 'North Indian', 3.7, 39, 950, 'Casual Dining', FALSE),
('J Spice', 'Banashankari', 'Bangalore', 'North Indian', 3.8, 59, 750, 'Casual Dining', TRUE),
('Swadesh Tadka', 'Banashankari', 'Bangalore', 'North Indian', 3.5, 179, 600, 'Casual Dining', TRUE),
('Iyer''s Tiffin Centre', 'Banashankari', 'Bangalore', 'South Indian', 3.8, 62, 150, 'Quick Bites', FALSE),
('Kydz Adda', 'Banashankari', 'Bangalore', 'Continental', 3.4, 6, 500, 'Casual Dining', FALSE),
('K27 - The Pub', 'Banashankari', 'Bangalore', 'Chinese', 3.1, 30, 1000, 'Bar', FALSE),
('Kotian Karavali Restaurant', 'Banashankari', 'Bangalore', 'South Indian', 3.5, 10, 300, 'Quick Bites', FALSE),
('Food Box Cafe', 'Banashankari', 'Bangalore', 'Mughlai', 3.6, 36, 500, 'Casual Dining', FALSE),
('Hide Out Cafe', 'Banashankari', 'Bangalore', 'Cafe', 3.7, 31, 300, 'Cafe', FALSE),
('CAFE NOVA', 'Banashankari', 'Bangalore', 'Cafe', 3.2, 11, 600, 'Cafe', FALSE),
('Darbar', 'Banashankari', 'Bangalore', 'North Indian', 3.0, 98, 800, 'Bar', FALSE),
('Sri Ganesh Juice and Chats', 'Banashankari', 'Bangalore', 'Juices', 3.5, 18, 150, 'Beverage Shop', FALSE),
('Manifest Cafe', 'Banashankari', 'Bangalore', 'South Indian', 3.5, 10, 500, 'Casual Dining', FALSE),
('Beijing Bites', 'Banashankari', 'Bangalore', 'Chinese', 2.7, 128, 850, 'Casual Dining', FALSE),
('The Pizzeria', 'Banashankari', 'Bangalore', 'Pizza', 2.8, 45, 800, 'Casual Dining', TRUE),
('Sri Krishna Sagar', 'Banashankari', 'Bangalore', 'North Indian', 3.2, 119, 400, 'Casual Dining', TRUE),
('Lassi Stop', 'Banashankari', 'Bangalore', 'Beverages', 3.4, 12, 150, 'Beverage Shop', TRUE),
('Sea Green Cafe', 'Banashankari', 'Bangalore', 'Cafe', 3.3, 4, 500, 'Cafe', FALSE),
('As On Fire', 'South Bangalore', 'Bangalore', 'Pizza', 3.5, 41, 400, 'Food Truck', TRUE),
('Pizza Hut', 'Banashankari', 'Bangalore', 'Pizza', 3.7, 405, 750, 'Casual Dining', TRUE),
('New Prashanth Hotel', 'Banashankari', 'Bangalore', 'Biryani', 3.9, 388, 650, 'Casual Dining', TRUE),
('Taaza Thindi', 'Banashankari', 'Bangalore', 'South Indian', 4.7, 651, 100, 'Quick Bites', FALSE),
('Ayodhya Upachar', 'Banashankari', 'Bangalore', 'South Indian', 4.3, 734, 200, 'Quick Bites', TRUE),
('Petoo', 'Banashankari', 'Bangalore', 'North Indian', 3.7, 21, 450, 'Quick Bites', FALSE),
('Roving Feast', 'Banashankari', 'Bangalore', 'Italian', 4.0, 1047, 450, 'Quick Bites', FALSE),
('KFC', 'Banashankari', 'Bangalore', 'Burger', 3.8, 505, 450, 'Quick Bites', TRUE),
('Five Star Chicken', 'Banashankari', 'Bangalore', 'Fast Food', 3.6, 55, 200, 'Quick Bites', FALSE),
('Gama Gama', 'Banashankari', 'Bangalore', 'South Indian', 3.9, 264, 200, 'Quick Bites', TRUE),
('Hotel New Karavali', 'Banashankari', 'Bangalore', 'Mangalorean', 3.8, 133, 300, 'Quick Bites', TRUE),
('McDonald''s', 'Banashankari', 'Bangalore', 'Burger', 3.9, 286, 500, 'Quick Bites', TRUE),
('Sri Laxmi Venkateshwara Coffee Bar', 'Banashankari', 'Bangalore', 'South Indian', 4.4, 343, 100, 'Quick Bites', FALSE),
('Bhattara Bhojana', 'Banashankari', 'Bangalore', 'South Indian', 3.6, 66, 150, 'Quick Bites', TRUE),
('Davanagere Benne Dose Hut', 'Banashankari', 'Bangalore', 'South Indian', 3.4, 10, 100, 'Quick Bites', TRUE),
('Utsav Restaurant', 'Banashankari', 'Bangalore', 'North Indian', 3.8, 61, 300, 'Quick Bites', TRUE),
('Messy Bowl', 'Banashankari', 'Bangalore', 'Fast Food', 3.8, 70, 500, 'Quick Bites', FALSE),
('Devanna Dum Biriyani Centre', 'Banashankari', 'Bangalore', 'Biryani', 3.6, 28, 300, 'Quick Bites', TRUE),
('Janahaar', 'Banashankari', 'Bangalore', 'South Indian', 3.8, 70, 100, 'Quick Bites', TRUE),
('Stop ''N'' Joy', 'Banashankari', 'Bangalore', 'Fast Food', 3.8, 28, 150, 'Quick Bites', TRUE),
('Dodda Mane Baaduta', 'Banashankari', 'Bangalore', 'North Indian', 3.5, 15, 250, 'Quick Bites', TRUE),
('Chickpet Donne Biryani House', 'Banashankari', 'Bangalore', 'Biryani', 3.8, 131, 250, 'Quick Bites', TRUE),
('Brahmin Cafe', 'Banashankari', 'Bangalore', 'South Indian', 3.8, 19, 150, 'Quick Bites', FALSE),
('Chumma Delicious', 'Banashankari', 'Bangalore', 'South Indian', 3.7, 237, 200, 'Quick Bites', TRUE),
('Udupi Upachar', 'Banashankari', 'Bangalore', 'South Indian', 3.3, 6, 500, 'Quick Bites', TRUE),
('Bengaluru Coffee House', 'Banashankari', 'Bangalore', 'South Indian', 4.1, 201, 300, 'Quick Bites', TRUE),
('Foodiction', 'Banashankari', 'Bangalore', 'North Indian', 2.8, 506, 500, 'Quick Bites', TRUE),
('The Biryani Cafe', 'Banashankari', 'Bangalore', 'Biryani', 4.1, 520, 300, 'Quick Bites', FALSE),
('Banashankari Donne Biriyani', 'Banashankari', 'Bangalore', 'Biryani', 3.8, 104, 300, 'Quick Bites', TRUE),
('Addhuri Udupi Bhojana', 'Banashankari', 'Bangalore', 'South Indian', 3.7, 88, 300, 'Quick Bites', FALSE),
('Vasanth Vihar - Since 1965', 'Banashankari', 'Bangalore', 'South Indian', 3.6, 95, 150, 'Quick Bites', TRUE),
('Subway', 'Banashankari', 'Bangalore', 'Salad', 3.7, 136, 600, 'Quick Bites', TRUE),
('SGS Non Veg - Gundu Pulav', 'Banashankari', 'Bangalore', 'Biryani', 3.8, 101, 400, 'Quick Bites', TRUE),
('Udupi Ruchi Grand', 'Banashankari', 'Bangalore', 'South Indian', 4.2, 60, 200, 'Quick Bites', TRUE),
('Hotel Mangala', 'Banashankari', 'Bangalore', 'South Indian', 3.9, 88, 250, 'Quick Bites', FALSE),
('Simple Thindies', 'Banashankari', 'Bangalore', 'South Indian', 3.5, 8, 200, 'Quick Bites', FALSE),
('Rolls On Wheels', 'Banashankari', 'Bangalore', 'Fast Food', 3.4, 145, 300, 'Quick Bites', FALSE),
('Chilli Flakes', 'Banashankari', 'Bangalore', 'Fast Food', 3.6, 46, 500, 'Quick Bites', TRUE),
('Kababs N Biryani', 'Banashankari', 'Bangalore', 'South Indian', 3.4, 22, 200, 'Quick Bites', TRUE),
('Udupi Ruchi', 'Banashankari', 'Bangalore', 'South Indian', 3.9, 57, 200, 'Quick Bites', TRUE),
('SLV Swadishta', 'Banashankari', 'Bangalore', 'South Indian', 3.8, 189, 300, 'Quick Bites', FALSE),
('Kolbeh', 'Banashankari', 'Bangalore', 'Fast Food', 3.7, 22, 500, 'Quick Bites', FALSE),
('Kolkata Kathi Roll''s', 'Banashankari', 'Bangalore', 'Fast Food', 3.6, 18, 250, 'Quick Bites', TRUE),
('Mylari Biryani Family Restaurant', 'Banashankari', 'Bangalore', 'Biryani', 3.7, 73, 400, 'Quick Bites', TRUE),
('Upahar Sagar', 'Banashankari', 'Bangalore', 'South Indian', 3.8, 39, 350, 'Quick Bites', FALSE),
('Domino''s Pizza', 'Banashankari', 'Bangalore', 'Pizza', 3.9, 540, 800, 'Quick Bites', TRUE),
('New Sagar Fast Food', 'Banashankari', 'Bangalore', 'North Indian', 3.6, 71, 250, 'Quick Bites', FALSE),
('Namma Biryani', 'Banashankari', 'Bangalore', 'Biryani', 3.6, 24, 250, 'Quick Bites', TRUE),
('Parama Ruchi', 'Banashankari', 'Bangalore', 'South Indian', 3.5, 11, 300, 'Quick Bites', FALSE),
('Thrilok Restaurant', 'Banashankari', 'Bangalore', 'Mangalorean', 3.4, 9, 350, 'Quick Bites', FALSE),
('Meat And Eat', 'Banashankari', 'Bangalore', 'Fast Food', 3.5, 12, 500, 'Quick Bites', FALSE),
('Ande Ka Funda', 'Banashankari', 'Bangalore', 'North Indian', 3.8, 120, 250, 'Quick Bites', TRUE),
('Dakshin Grand', 'Banashankari', 'Bangalore', 'South Indian', 3.0, 82, 300, 'Quick Bites', TRUE),
('Chicken Hunt', 'Banashankari', 'Bangalore', 'South Indian', 3.5, 88, 350, 'Quick Bites', TRUE),
('Maruthi Davangere Benne Dosa', 'Banashankari', 'Bangalore', 'South Indian', 4.0, 17, 150, 'Quick Bites', TRUE),
('Pizza Stop', 'Banashankari', 'Bangalore', 'Pizza', 3.0, 87, 600, 'Quick Bites', TRUE),
('Madhappa Hindu Military Hotel', 'Banashankari', 'Bangalore', 'South Indian', 3.4, 14, 300, 'Quick Bites', TRUE),
('Krishna Sagar', 'Banashankari', 'Bangalore', 'North Indian', 3.5, 31, 200, 'Quick Bites', FALSE),
('Hanumanthanagar Biryani Junction', 'Banashankari', 'Bangalore', 'South Indian', 3.5, 17, 300, 'Quick Bites', FALSE),
('Faasos', 'Banashankari', 'Bangalore', 'North Indian', 4.2, 415, 500, 'Quick Bites', TRUE),
('Rasoi', 'Banashankari', 'Bangalore', 'North Indian', 3.3, 128, 300, 'Quick Bites', TRUE),
('SLV Refreshment', 'Banashankari', 'Bangalore', 'South Indian', 4.1, 94, 100, 'Quick Bites', FALSE),
('Kaggis', 'Banashankari', 'Bangalore', 'Fast Food', 3.8, 64, 250, 'Quick Bites', FALSE),
('Chatar Patar', 'Banashankari', 'Bangalore', 'Fast Food', 3.7, 65, 300, 'Quick Bites', FALSE),
('Seven Star', 'Banashankari', 'Bangalore', 'North Indian', 3.4, 7, 250, 'Quick Bites', TRUE),
('SVKP Daily Fresh', 'Banashankari', 'Bangalore', 'South Indian', 3.3, 5, 350, 'Quick Bites', FALSE),
('Kidambi''s Kitchen', 'Banashankari', 'Bangalore', 'South Indian', 3.5, 52, 300, 'Quick Bites', FALSE),
('Ruchi''s Corner', 'Banashankari', 'Bangalore', 'Fast Food', 2.7, 123, 200, 'Quick Bites', TRUE),
('Tandoori Knight', 'Banashankari', 'Bangalore', 'North Indian', 3.0, 290, 450, 'Quick Bites', TRUE),
('Utsav', 'Banashankari', 'Bangalore', 'North Indian', 3.7, 59, 200, 'Quick Bites', TRUE),
('Mane Thindi', 'Banashankari', 'Bangalore', 'South Indian', 3.7, 130, 200, 'Quick Bites', FALSE),
('Fast And Fresh', 'Banashankari', 'Bangalore', 'North Indian', 2.8, 91, 400, 'Quick Bites', TRUE),
('New Gowda''s Fried Chicken', 'Banashankari', 'Bangalore', 'Biryani', 3.3, 12, 300, 'Quick Bites', TRUE),
('Juicy Momos', 'Banashankari', 'Bangalore', 'Tibetan', 3.5, 80, 250, 'Quick Bites', TRUE),
('Donne Biriyani House', 'Banashankari', 'Bangalore', 'South Indian', 3.9, 441, 400, 'Quick Bites', TRUE),
('Srinagar Kabab Corner', 'Banashankari', 'Bangalore', 'North Indian', 3.4, 10, 250, 'Quick Bites', FALSE),
('Sri Venkateshwara Chat Centre', 'Banashankari', 'Bangalore', 'Street Food', 3.5, 12, 100, 'Quick Bites', FALSE),
('Vinay Bhel Corner', 'Banashankari', 'Bangalore', 'Street Food', 3.4, 7, 100, 'Quick Bites', FALSE),
('Spice 9', 'Banashankari', 'Bangalore', 'Biryani', 3.4, 8, 300, 'Quick Bites', FALSE),
('Naveen Kabab & Biriyani Mane', 'Banashankari', 'Bangalore', 'Biryani', 3.2, 9, 300, 'Quick Bites', FALSE),
('Nandi Chats and Juice', 'Banashankari', 'Bangalore', 'Street Food', 3.6, 47, 150, 'Quick Bites', FALSE),
('Atithi Point Ande Ka Funda', 'Banashankari', 'Bangalore', 'North Indian', 3.1, 29, 150, 'Quick Bites', FALSE),
('Just Shawarma', 'Banashankari', 'Bangalore', 'Arabian', 3.8, 66, 300, 'Quick Bites', TRUE),
('Aramane Donne Biryani', 'Banashankari', 'Bangalore', 'Biryani', 3.1, 28, 200, 'Quick Bites', TRUE),
('FOOD ADDA', 'Banashankari', 'Bangalore', 'Fast Food', 3.2, 4, 200, 'Quick Bites', FALSE),
('New Mangalore Lunch Home', 'Banashankari', 'Bangalore', 'Mangalorean', 3.3, 7, 200, 'Quick Bites', FALSE),
('Hotel Nisarga', 'Banashankari', 'Bangalore', 'North Indian', 3.2, 5, 250, 'Quick Bites', FALSE),
('Coffee Bytes', 'Banashankari', 'Bangalore', 'Fast Food', 3.1, 6, 100, 'Quick Bites', FALSE),
('Parjanya Chat Zone', 'Banashankari', 'Bangalore', 'Street Food', 3.3, 17, 200, 'Quick Bites', FALSE),
('Yo Roll Corner', 'Banashankari', 'Bangalore', 'Street Food', 3.0, 27, 200, 'Quick Bites', FALSE),
('New Quality Dum Biryani', 'Banashankari', 'Bangalore', 'Biryani', 3.1, 9, 200, 'Quick Bites', FALSE),
('Sri Lakshmi Kabab Center', 'Banashankari', 'Bangalore', 'Kebab', 3.3, 4, 200, 'Quick Bites', FALSE),
('Tasty Bites', 'Banashankari', 'Bangalore', 'Fast Food', 3.7, 21, 150, 'Quick Bites', FALSE),
('Raams Chicken', 'Banashankari', 'Bangalore', 'Andhra', 3.6, 22, 300, 'Quick Bites', FALSE),
('Panchami', 'Banashankari', 'Bangalore', 'North Indian', 3.0, 15, 300, 'Quick Bites', FALSE),
('VEGeatz', 'Banashankari', 'Bangalore', 'South Indian', 3.4, 19, 200, 'Quick Bites', TRUE),
('Grand Food', 'Banashankari', 'Bangalore', 'South Indian', 3.4, 8, 250, 'Quick Bites', TRUE),
('Matru Sagar', 'Banashankari', 'Bangalore', 'South Indian', 3.6, 84, 250, 'Quick Bites', TRUE),
('Kavali', 'Banashankari', 'Bangalore', 'South Indian', 4.0, 42, 300, 'Quick Bites', FALSE),
('Bunt''s Biriyani Palace', 'Banashankari', 'Bangalore', 'North Indian', 3.0, 213, 400, 'Quick Bites', TRUE),
('Funjabi Curries', 'Banashankari', 'Bangalore', 'North Indian', 2.9, 11, 500, 'Quick Bites', TRUE),
('Udupi Upahar', 'Banashankari', 'Bangalore', 'South Indian', 3.8, 58, 300, 'Quick Bites', TRUE),
('Ranganna Military Hotel', 'Jayanagar', 'Bangalore', 'South Indian', 4.2, 725, 350, 'Quick Bites', FALSE),
('Roti Ghar', 'Basavanagudi', 'Bangalore', 'North Indian', 3.9, 750, 500, 'Casual Dining', TRUE),
('Grand Village', 'Basavanagudi', 'Bangalore', 'North Indian', 3.8, 166, 600, 'Casual Dining', FALSE),
('Vidyarthi Bhavan', 'Basavanagudi', 'Bangalore', 'South Indian', 4.4, 4460, 150, 'Quick Bites', FALSE),
('Bharjari Oota', 'Basavanagudi', 'Bangalore', 'South Indian', 3.9, 153, 350, 'Casual Dining', FALSE),
('Gokul Veg', 'Basavanagudi', 'Bangalore', 'North Indian', 3.8, 469, 750, 'Casual Dining', TRUE),
('SLV Corner Restaurant', 'Basavanagudi', 'Bangalore', 'South Indian', 4.1, 364, 550, 'Casual Dining', TRUE),
('Timepass Dinner', 'Basavanagudi', 'Bangalore', 'North Indian', 3.8, 286, 600, 'Casual Dining', TRUE),
('Baisakhi', 'Basavanagudi', 'Bangalore', 'North Indian', 3.8, 527, 500, 'Casual Dining', TRUE),
('Eat Repeat', 'Basavanagudi', 'Bangalore', 'South Indian', 3.9, 101, 150, 'Quick Bites', TRUE),
('Sri Guru Kottureshwara Davangere Benne Dosa', 'Basavanagudi', 'Bangalore', 'South Indian', 4.1, 558, 150, 'Quick Bites', TRUE),
('Bridgeway', 'Mysore Road', 'Bangalore', 'North Indian', 3.8, 94, 550, 'Casual Dining', FALSE),
('Srinathji''s Cafe', 'Basavanagudi', 'Bangalore', 'North Indian', 3.8, 148, 550, 'Casual Dining', FALSE),
('Soho Bar & Grill', 'Basavanagudi', 'Bangalore', 'North Indian', 2.7, 377, 1100, 'Pub', FALSE),
('Kollapuri''s', 'Basavanagudi', 'Bangalore', 'South Indian', 3.9, 206, 450, 'Quick Bites', FALSE),
('Aadhya Hotel', 'Basavanagudi', 'Bangalore', 'South Indian', 3.3, 5, 800, 'Casual Dining', TRUE),
('Bhavani Restaurant', 'Basavanagudi', 'Bangalore', 'South Indian', 3.9, 100, 300, 'Quick Bites', FALSE),
('Puliyogare Point', 'Basavanagudi', 'Bangalore', 'South Indian', 4.2, 444, 100, 'Quick Bites', TRUE),
('Zephyr', 'Basavanagudi', 'Bangalore', 'Italian', 3.9, 133, 650, 'Casual Dining', FALSE),
('Redberrys', 'Basavanagudi', 'Bangalore', 'Cafe', 4.0, 219, 600, 'Cafe', TRUE),
('Hotel Dwarka', 'Basavanagudi', 'Bangalore', 'South Indian', 4.2, 253, 250, 'Quick Bites', FALSE),
('Nisarga Garden Restaurant', 'Basavanagudi', 'Bangalore', 'South Indian', 3.4, 51, 350, 'Quick Bites', FALSE),
('Ma-Arya Family Restaurant', 'Basavanagudi', 'Bangalore', 'Biryani', 3.7, 61, 600, 'Casual Dining', FALSE),
('A2B - Adyar Ananda Bhavan', 'Mysore Road', 'Bangalore', 'South Indian', 3.8, 155, 400, 'Casual Dining', TRUE),
('Ragoo''s', 'Jayanagar', 'Bangalore', 'Italian', 3.9, 233, 800, 'Casual Dining', TRUE),
('Imperial Restaurant', 'Mysore Road', 'Bangalore', 'North Indian', 3.7, 264, 750, 'Casual Dining', TRUE),
('New Prashanth Hotel', 'Basavanagudi', 'Bangalore', 'South Indian', 3.9, 66, 400, 'Casual Dining', FALSE),
('Udupi Sri Krishna Bhavan', 'Basavanagudi', 'Bangalore', 'South Indian', 4.1, 238, 600, 'Quick Bites', FALSE),
('Chinese Kitchen', 'Basavanagudi', 'Bangalore', 'Chinese', 3.8, 58, 150, 'Quick Bites', TRUE),
('Vijayalakshmi', 'Basavanagudi', 'Bangalore', 'South Indian', 3.9, 47, 200, 'Quick Bites', TRUE),
('Nammura Donne Biriyani', 'Basavanagudi', 'Bangalore', 'Biryani', 3.5, 155, 400, 'Quick Bites', TRUE),
('Curry Leaves', 'Basavanagudi', 'Bangalore', 'Andhra', 4.1, 176, 800, 'Casual Dining', TRUE),
('Goli Vada Pav No. 1', 'Basavanagudi', 'Bangalore', 'Street Food', 3.7, 93, 200, 'Quick Bites', TRUE),
('Ice Thunder', 'Basavanagudi', 'Bangalore', 'South Indian', 3.8, 124, 300, 'Quick Bites', FALSE),
('South Kitchen', 'Basavanagudi', 'Bangalore', 'South Indian', 4.3, 275, 100, 'Quick Bites', TRUE),
('Upahara Darshini', 'Basavanagudi', 'Bangalore', 'South Indian', 4.2, 254, 150, 'Quick Bites', FALSE),
('Mahalaxmi Tiffin Room', 'Basavanagudi', 'Bangalore', 'South Indian', 4.1, 177, 100, 'Quick Bites', FALSE),
('Starlite Bakery & Fastfood', 'Jayanagar', 'Bangalore', 'North Indian', 3.7, 23, 300, 'Quick Bites', TRUE),
('Sandwichwallas', 'Basavanagudi', 'Bangalore', 'Fast Food', 4.0, 132, 200, 'Quick Bites', TRUE),
('J K Fish Land', 'Jayanagar', 'Bangalore', 'Seafood', 3.6, 35, 300, 'Quick Bites', TRUE),
('Udupi Grand', 'Basavanagudi', 'Bangalore', 'South Indian', 3.8, 74, 300, 'Quick Bites', TRUE),
('Chinese Square', 'Basavanagudi', 'Bangalore', 'Chinese', 3.9, 38, 200, 'Quick Bites', TRUE),
('Castle Rock', 'Uttarahalli', 'Bangalore', 'North Indian', 3.6, 172, 700, 'Casual Dining', TRUE),
('Swadd Kitchen', 'Basavanagudi', 'Bangalore', 'North Indian', 3.4, 4, 500, 'Casual Dining', TRUE),
('Kamat Bugle Rock', 'Basavanagudi', 'Bangalore', 'South Indian', 3.9, 543, 300, 'Quick Bites', TRUE),
('Basavanagudi Mylari', 'Basavanagudi', 'Bangalore', 'South Indian', 4.0, 52, 300, 'Quick Bites', FALSE),
('RS Shiv Sagar', 'Basavanagudi', 'Bangalore', 'North Indian', 3.7, 217, 450, 'Casual Dining', FALSE),
('New Prashanth Hotel', 'Basavanagudi', 'Bangalore', 'South Indian', 2.9, 34, 750, 'Casual Dining', FALSE),
('Shrinidhi Military Hotel', 'Basavanagudi', 'Bangalore', 'North Indian', 3.3, 6, 300, 'Quick Bites', FALSE),
('Dakshin Kitchen', 'Basavanagudi', 'Bangalore', 'South Indian', 3.6, 15, 100, 'Quick Bites', TRUE),
('Pramukh Family Restaurant', 'Basavanagudi', 'Bangalore', 'North Indian', 3.9, 111, 700, 'Casual Dining', FALSE),
('Chaatimes', 'Basavanagudi', 'Bangalore', 'Street Food', 3.8, 133, 200, 'Quick Bites', TRUE),
('Vybhava', 'Jayanagar', 'Bangalore', 'South Indian', 3.8, 39, 250, 'Quick Bites', FALSE),
('Shree Venkateshwara North Karnataka Hotel', 'Basavanagudi', 'Bangalore', 'South Indian', 4.0, 64, 200, 'Quick Bites', FALSE),
('Kadamba Classic', 'Mysore Road', 'Bangalore', 'South Indian', 3.6, 16, 300, 'Quick Bites', FALSE),
('Food Geek', 'Basavanagudi', 'Bangalore', 'Sandwich', 3.8, 25, 350, 'Quick Bites', TRUE),
('Rosewood International Hotel - Bar & Restaurant', 'Mysore Road', 'Bangalore', 'North Indian', 3.6, 8, 800, 'Casual Dining', FALSE),
('Anand Sagar Inn', 'Basavanagudi', 'Bangalore', 'South Indian', 3.3, 6, 450, 'Casual Dining', FALSE),
('Sangam Military Hotel', 'Jayanagar', 'Bangalore', 'South Indian', 3.2, 14, 250, 'Quick Bites', FALSE),
('Kholi Mane', 'Basavanagudi', 'Bangalore', 'Andhra', 3.6, 46, 450, 'Quick Bites', FALSE),
('Harshi Super Sandwich', 'Basavanagudi', 'Bangalore', 'Fast Food', 3.8, 148, 150, 'Quick Bites', FALSE),
('Hotel Pork Paradise', 'Mysore Road', 'Bangalore', 'South Indian', 3.7, 21, 300, 'Quick Bites', TRUE),
('Belly Squad Food Truck', 'South Bangalore', 'Bangalore', 'Chinese', 3.8, 55, 300, 'Food Truck', FALSE),
('New Rajadhani Spicy', 'Kumaraswamy Layout', 'Bangalore', 'North Indian', 3.7, 67, 700, 'Casual Dining', TRUE),
('Matru Sagar', 'Mysore Road', 'Bangalore', 'South Indian', 3.7, 31, 300, 'Quick Bites', TRUE),
('Sri Udupi Veg', 'Jayanagar', 'Bangalore', 'South Indian', 3.3, 4, 250, 'Quick Bites', FALSE),
('50-50 EATING HOUSE', 'Basavanagudi', 'Bangalore', 'South Indian', 3.2, 4, 100, 'Quick Bites', FALSE),
('Om Shiva Shakthi Chats Centre', 'Basavanagudi', 'Bangalore', 'Street Food', 3.9, 26, 300, 'Quick Bites', FALSE),
('Juice Junction Food Court', 'Basavanagudi', 'Bangalore', 'Juices', 3.7, 57, 200, 'Quick Bites', TRUE),
('Burger King', 'Basavanagudi', 'Bangalore', 'Burger', 3.2, 71, 600, 'Quick Bites', TRUE),
('Rolls Corner', 'Basavanagudi', 'Bangalore', 'Fast Food', 3.6, 22, 150, 'Quick Bites', FALSE),
('New Ambur Hot Dum Biryani', 'Mysore Road', 'Bangalore', 'Biryani', 3.2, 8, 150, 'Quick Bites', FALSE),
('Shri Vinayaka Ice N Juice', 'Basavanagudi', 'Bangalore', 'Beverages', 3.2, 11, 150, 'Quick Bites', TRUE),
('Happy Chopsticks', 'Basavanagudi', 'Bangalore', 'Chinese', 3.6, 17, 300, 'Quick Bites', TRUE),
('Jcubez', 'Banashankari', 'Bangalore', 'Finger Food', 3.8, 977, 1300, 'Lounge', FALSE),
('Gustoes Beer House', 'Banashankari', 'Bangalore', 'Continental', 4.1, 868, 1200, 'Pub', FALSE),
('Blue Wings Bar & Restaurant', 'Banashankari', 'Bangalore', 'North Indian', 3.7, 43, 700, 'Bar', FALSE),
('Vi Ra''s Bar and Restaurant', 'Banashankari', 'Bangalore', 'South Indian', 3.3, 62, 800, 'Bar', FALSE),
('K27 - The Pub', 'Banashankari', 'Bangalore', 'Chinese', 3.1, 30, 1000, 'Bar', FALSE),
('Darbar', 'Banashankari', 'Bangalore', 'North Indian', 3.0, 98, 800, 'Bar', FALSE),
('Soho Bar & Grill', 'Basavanagudi', 'Bangalore', 'North Indian', 2.7, 377, 1100, 'Pub', FALSE),
('Deja Vu Resto Bar', 'Bannerghatta Road', 'Bangalore', 'North Indian', 4.4, 2487, 900, 'Pub', TRUE),
('Fattoush', 'Bannerghatta Road', 'Bangalore', 'Arabian', 4.2, 1964, 1000, 'Casual Dining', TRUE),
('Empire Restaurant', 'Bannerghatta Road', 'Bangalore', 'North Indian', 4.3, 3178, 750, 'Casual Dining', TRUE),
('Abhiruchi Hotel', 'Bannerghatta Road', 'Bangalore', 'Andhra', 3.3, 455, 550, 'Casual Dining', TRUE),
('Tulips', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.1, 19, 800, 'Casual Dining', FALSE),
('Barbeque Nation', 'JP Nagar', 'Bangalore', 'North Indian', 4.7, 3845, 1600, 'Casual Dining', FALSE),
('Sattvam', 'JP Nagar', 'Bangalore', 'North Indian', 4.3, 353, 1200, 'Casual Dining', FALSE),
('24th Main', 'JP Nagar', 'Bangalore', 'North Indian', 4.1, 1234, 800, 'Casual Dining', FALSE),
('Zaitoon', 'JP Nagar', 'Bangalore', 'BBQ', 4.1, 1538, 1000, 'Casual Dining', TRUE),
('Mango Greens', 'JP Nagar', 'Bangalore', 'North Indian', 3.9, 49, 900, 'Casual Dining', FALSE),
('Oye Amritsar', 'JP Nagar', 'Bangalore', 'North Indian', 3.8, 756, 1000, 'Casual Dining', TRUE),
('Melt - Eden Park', 'JP Nagar', 'Bangalore', 'North Indian', 4.0, 347, 1000, 'Casual Dining', TRUE),
('Spice Code', 'JP Nagar', 'Bangalore', 'South Indian', 4.0, 165, 1000, 'Casual Dining', FALSE),
('The Onyx - The HHI Select Bengaluru', 'JP Nagar', 'Bangalore', 'North Indian', 3.3, 177, 950, 'Casual Dining', FALSE),
('The Pavillion', 'JP Nagar', 'Bangalore', 'North Indian', 2.7, 43, 1000, 'Casual Dining', FALSE),
('Sankranthi Veg Restaurant', 'BTM', 'Bangalore', 'South Indian', 3.0, 102, 600, 'Casual Dining', TRUE),
('Tisano Cafe', 'Bannerghatta Road', 'Bangalore', 'Cafe', 3.8, 54, 500, 'Cafe', TRUE),
('Cafe Kabana', 'Bannerghatta Road', 'Bangalore', 'Cafe', 4.0, 200, 700, 'Cafe', FALSE),
('Butterly', 'Bannerghatta Road', 'Bangalore', 'Cafe', 3.9, 102, 450, 'Cafe', TRUE),
('Black Mug Cafe', 'Bannerghatta Road', 'Bangalore', 'Cafe', 3.7, 171, 300, 'Cafe', TRUE),
('#refuel', 'Bannerghatta Road', 'Bangalore', 'Cafe', 3.7, 37, 400, 'Cafe', TRUE),
('WAFL', 'Bannerghatta Road', 'Bangalore', 'Cafe', 3.9, 40, 400, 'Food Court', TRUE),
('Vaho Kafe & Pressery', 'Bannerghatta Road', 'Bangalore', 'Cafe', 3.9, 125, 500, 'Cafe', FALSE),
('Dreamcatcher', 'Bannerghatta Road', 'Bangalore', 'Cafe', 3.9, 49, 600, 'Cafe', TRUE),
('Cafe Coffee Day', 'Bannerghatta Road', 'Bangalore', 'Cafe', 3.6, 19, 900, 'Cafe', FALSE),
('Cafe Arabica', 'Bannerghatta Road', 'Bangalore', 'Cafe', 3.8, 69, 700, 'Cafe', FALSE),
('Starbucks', 'Bannerghatta Road', 'Bangalore', 'Cafe', 3.9, 52, 700, 'Cafe', FALSE),
('Smoor', 'Bannerghatta Road', 'Bangalore', 'Desserts', 3.6, 18, 900, 'Dessert Parlor', TRUE),
('Kalmane Koffees', 'Bannerghatta Road', 'Bangalore', 'Cafe', 3.9, 78, 350, 'Cafe', FALSE),
('Shee-Sha Cafe', 'Bannerghatta Road', 'Bangalore', 'Cafe', 3.6, 39, 800, 'Cafe', FALSE),
('Brews N Bites', 'Bannerghatta Road', 'Bangalore', 'Chinese', 2.7, 48, 650, 'Quick Bites', TRUE),
('D2V Cafe', 'Bannerghatta Road', 'Bangalore', 'Cafe', 3.6, 13, 700, 'Cafe', FALSE),
('Cafe Talk', 'Bannerghatta Road', 'Bangalore', 'Cafe', 3.3, 14, 700, 'Cafe', FALSE),
('Cafe Choco Craze', 'Bannerghatta Road', 'Bangalore', 'Cafe', 3.7, 9, 400, 'Cafe', FALSE),
('Slate Cafe', 'JP Nagar', 'Bangalore', 'Cafe', 4.1, 46, 600, 'Cafe', TRUE),
('Dialogues', 'JP Nagar', 'Bangalore', 'Cafe', 4.0, 129, 600, 'Cafe', FALSE),
('Mudpipe Cafe', 'JP Nagar', 'Bangalore', 'Cafe', 3.9, 727, 800, 'Cafe', TRUE),
('TAB - Take A Break', 'JP Nagar', 'Bangalore', 'Cafe', 4.1, 521, 550, 'Cafe', FALSE),
('Biggies Burger ''n'' More', 'JP Nagar', 'Bangalore', 'Cafe', 4.1, 203, 650, 'Quick Bites', TRUE),
('Onesta', 'JP Nagar', 'Bangalore', 'Pizza', 4.4, 4381, 600, 'Casual Dining', TRUE),
('Cafe Potpourri', 'JP Nagar', 'Bangalore', 'Cafe', 3.7, 131, 400, 'Cafe', TRUE),
('De Oxford Cafe', 'JP Nagar', 'Bangalore', 'Cafe', 3.7, 34, 500, 'Cafe', FALSE),
('Vinaya Coffee Moments', 'JP Nagar', 'Bangalore', 'Burger', 3.7, 46, 450, 'Cafe', TRUE),
('Brew Point', 'JP Nagar', 'Bangalore', 'Cafe', 3.6, 10, 500, 'Cafe', TRUE),
('The Cravery', 'JP Nagar', 'Bangalore', 'Continental', 2.6, 18, 500, 'Cafe', TRUE),
('Cuppa', 'JP Nagar', 'Bangalore', 'Cafe', 3.4, 48, 550, 'Cafe', FALSE),
('Anju''s Cafe', 'JP Nagar', 'Bangalore', 'Cafe', 3.4, 6, 600, 'Cafe', FALSE),
('Skytouch Le Cafe', 'JP Nagar', 'Bangalore', 'Cafe', 3.7, 127, 700, 'Cafe', TRUE),
('Woodee Pizza', 'JP Nagar', 'Bangalore', 'Cafe', 2.7, 85, 500, 'Cafe', TRUE),
('Hearts Unlock Cafe', 'BTM', 'Bangalore', 'Cafe', 3.2, 11, 500, 'Cafe', FALSE),
('eat.fit', 'BTM', 'Bangalore', 'Healthy Food', 4.5, 1178, 500, 'Delivery', TRUE),
('Sai Abhiruchi', 'BTM', 'Bangalore', 'Andhra', 3.7, 335, 800, 'Casual Dining', TRUE),
('Capsicum Family Restaurant', 'BTM', 'Bangalore', 'Biryani', 3.8, 254, 800, 'Casual Dining', TRUE),
('Box Magic', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.6, 21, 400, 'Quick Bites', TRUE),
('Maa''r Rannaghor', 'JP Nagar', 'Bangalore', 'Bengali', 3.8, 20, 400, 'Quick Bites', TRUE),
('Easy Bites', 'JP Nagar', 'Bangalore', 'Fast Food', 4.1, 63, 300, 'Takeaway', TRUE),
('Hiyar Majhe Kolkata', 'BTM', 'Bangalore', 'Bengali', 4.0, 244, 400, 'Quick Bites', TRUE),
('Dabba Gosht', 'JP Nagar', 'Bangalore', 'Arabian', 3.4, 9, 400, 'Takeaway', TRUE),
('Empire Restaurant', 'JP Nagar', 'Bangalore', 'Kerala', 3.6, 113, 400, 'Takeaway', TRUE),
('Punjabites', 'JP Nagar', 'Bangalore', 'North Indian', 3.7, 5, 400, 'Takeaway', TRUE),
('Sri Lakshmi Dhaba', 'BTM', 'Bangalore', 'North Indian', 2.9, 255, 250, 'Quick Bites', TRUE),
('XO Belgian Waffle', 'BTM', 'Bangalore', 'Desserts', 4.5, 549, 400, 'Dessert Parlor', TRUE),
('Swadista Aahar', 'BTM', 'Bangalore', 'South Indian', 4.1, 775, 300, 'Quick Bites', TRUE),
('Vegetarea', 'BTM', 'Bangalore', 'South Indian', 3.9, 38, 250, 'Takeaway', TRUE),
('Al-Bek', 'JP Nagar', 'Bangalore', 'Biryani', 3.6, 208, 300, 'Takeaway', TRUE),
('Aniram''s', 'JP Nagar', 'Bangalore', 'Chinese', 4.1, 739, 500, 'Delivery', TRUE),
('Punjabi Nawabi', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.8, 310, 400, 'Quick Bites', TRUE),
('YummRajj', 'BTM', 'Bangalore', 'Fast Food', 3.3, 42, 500, 'Quick Bites', TRUE),
('Swad Punjab Da', 'BTM', 'Bangalore', 'North Indian', 4.0, 126, 150, 'Quick Bites', TRUE),
('BOX8- Desi Meals', 'Bannerghatta Road', 'Bangalore', 'North Indian', 4.1, 427, 500, 'Takeaway', TRUE),
('Roti Wala', 'BTM', 'Bangalore', 'North Indian', 4.0, 197, 300, 'Quick Bites', TRUE),
('Midnight Mania', 'BTM', 'Bangalore', 'Pizza', 4.1, 601, 700, 'Quick Bites', TRUE),
('Kitchens@JP Nagar', 'JP Nagar', 'Bangalore', 'Biryani', 3.9, 488, 400, 'Takeaway', TRUE),
('Krishna Kuteera', 'Bannerghatta Road', 'Bangalore', 'South Indian', 4.0, 396, 400, 'Quick Bites', TRUE),
('Apna Punjab', 'BTM', 'Bangalore', 'North Indian', 3.6, 474, 450, 'Quick Bites', TRUE),
('Paratha Junction', 'BTM', 'Bangalore', 'North Indian', 2.9, 172, 300, 'Quick Bites', TRUE),
('Nellore Bhojanam', 'Bannerghatta Road', 'Bangalore', 'Andhra', 3.1, 175, 250, 'Quick Bites', TRUE),
('Momoz', 'BTM', 'Bangalore', 'Chinese', 4.0, 939, 600, 'Casual Dining', TRUE),
('Kalingas', 'BTM', 'Bangalore', 'Oriya', 3.9, 173, 250, 'Quick Bites', TRUE),
('Kanteen The Eatery', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.9, 77, 400, 'Quick Bites', TRUE),
('Kullad Cafe', 'BTM', 'Bangalore', 'North Indian', 3.9, 326, 200, 'Cafe', TRUE),
('Donne Biriyani House', 'JP Nagar', 'Bangalore', 'Biryani', 3.3, 212, 350, 'Quick Bites', TRUE),
('Litti Twist', 'BTM', 'Bangalore', 'North Indian', 4.1, 464, 300, 'Quick Bites', TRUE),
('FreshMenu', 'Bannerghatta Road', 'Bangalore', 'Healthy Food', 3.3, 628, 450, 'Delivery', TRUE),
('Shanthi Sagar', 'JP Nagar', 'Bangalore', 'South Indian', 3.6, 518, 400, 'Casual Dining', TRUE),
('Cakebuy', 'Bannerghatta Road', 'Bangalore', 'Desserts', 3.9, 70, 350, 'Dessert Parlor', TRUE),
('Five Star Chicken', 'JP Nagar', 'Bangalore', 'Burger', 3.9, 62, 300, 'Quick Bites', TRUE),
('Corner House Ice Cream', 'Jayanagar', 'Bangalore', 'Ice Cream', 4.4, 819, 400, 'Dessert Parlor', TRUE),
('Delight Food', 'BTM', 'Bangalore', 'Andhra', 2.6, 171, 450, 'Casual Dining', TRUE),
('Andhra Kitchen', 'Bannerghatta Road', 'Bangalore', 'Andhra', 3.9, 158, 400, 'Takeaway', TRUE),
('Veg By Nature', 'JP Nagar', 'Bangalore', 'North Indian', 3.4, 14, 200, 'Takeaway', TRUE),
('Fattoush', 'Bannerghatta Road', 'Bangalore', 'Arabian', 4.2, 1964, 1000, 'Casual Dining', TRUE),
('Chicken Magic', 'BTM', 'Bangalore', 'Chinese', 3.7, 207, 300, 'Quick Bites', TRUE),
('Behrouz Biryani', 'Bannerghatta Road', 'Bangalore', 'Biryani', 4.0, 138, 650, 'Delivery', TRUE),
('Abhiruchi Hotel', 'Bannerghatta Road', 'Bangalore', 'Andhra', 3.3, 455, 550, 'Casual Dining', TRUE),
('Swathi Restaurant', 'JP Nagar', 'Bangalore', 'Andhra', 3.9, 14, 400, 'Takeaway', TRUE),
('Fresh Kitchen', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.4, 13, 600, 'Casual Dining', TRUE),
('Hind Ka Chulah', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.8, 181, 600, 'Food Court', TRUE),
('Kuttanad', 'Bannerghatta Road', 'Bangalore', 'Kerala', 3.6, 140, 200, 'Quick Bites', TRUE),
('New Mahesh Friends Food Corner', 'BTM', 'Bangalore', 'North Indian', 3.2, 44, 300, 'Quick Bites', TRUE),
('Bohra Bohra CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ©', 'JP Nagar', 'Bangalore', 'Bohri', 3.6, 43, 300, 'Quick Bites', TRUE),
('Pizza Hut', 'JP Nagar', 'Bangalore', 'Pizza', 2.7, 159, 750, 'Quick Bites', TRUE),
('Shree Krishna Sannidhi', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.4, 76, 450, 'Quick Bites', TRUE),
('BingeJoy!', 'JP Nagar', 'Bangalore', 'Biryani', 3.6, 16, 100, 'Kiosk', TRUE),
('Shiv Sai Hotel', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.5, 74, 400, 'Quick Bites', TRUE),
('MRA', 'BTM', 'Bangalore', 'Bakery', 3.9, 20, 200, 'Takeaway', TRUE),
('Beijing Bites', 'JP Nagar', 'Bangalore', 'Chinese', 3.7, 9, 400, 'Takeaway', TRUE),
('A2B - Adyar Ananda Bhavan', 'JP Nagar', 'Bangalore', 'South Indian', 4.1, 51, 200, 'Takeaway', TRUE),
('Burj Hotel', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.5, 53, 350, 'Quick Bites', TRUE),
('Shaadi Ki Biryani', 'BTM', 'Bangalore', 'Biryani', 3.1, 28, 400, 'Takeaway', TRUE),
('Subway', 'Bannerghatta Road', 'Bangalore', 'Salad', 3.2, 166, 600, 'Quick Bites', TRUE),
('Madeena Hotel', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.9, 50, 400, 'Quick Bites', TRUE),
('Biryani Durbar', 'Bannerghatta Road', 'Bangalore', 'Biryani', 3.7, 128, 400, 'Takeaway', TRUE),
('The Good Bowl', 'Bannerghatta Road', 'Bangalore', 'Italian', 3.6, 8, 500, 'Takeaway', TRUE),
('Mahesh Friends Food Center', 'BTM', 'Bangalore', 'Chinese', 2.9, 126, 300, 'Quick Bites', TRUE),
('Juice Shop', 'JP Nagar', 'Bangalore', 'Juices', 3.4, 24, 150, 'Takeaway', TRUE),
('Kabab Magic', 'Jayanagar', 'Bangalore', 'North Indian', 4.0, 952, 400, 'Quick Bites', TRUE),
('Nammura Donne Biriyani', 'Kanakapura Road', 'Bangalore', 'Biryani', 3.4, 51, 400, 'Quick Bites', TRUE),
('Burger King', 'Bannerghatta Road', 'Bangalore', 'Burger', 3.8, 472, 600, 'Quick Bites', TRUE),
('Dadi''s Dum Biryani', 'Bannerghatta Road', 'Bangalore', 'Biryani', 4.0, 739, 800, 'Casual Dining', TRUE),
('Krishna Kuteera South', 'Bannerghatta Road', 'Bangalore', 'South Indian', 4.0, 117, 500, 'Casual Dining', TRUE),
('Alankrutha', 'BTM', 'Bangalore', 'Andhra', 3.9, 255, 500, 'Casual Dining', TRUE),
('Paradise', 'JP Nagar', 'Bangalore', 'Biryani', 4.0, 1974, 800, 'Casual Dining', TRUE),
('Kabab Mehal', 'JP Nagar', 'Bangalore', 'Kebab', 3.7, 65, 400, 'Quick Bites', TRUE),
('Mughlai Kitchen', 'BTM', 'Bangalore', 'Mughlai', 3.5, 269, 600, '', TRUE),
('Andhra Ruchulu', 'JP Nagar', 'Bangalore', 'Andhra', 4.2, 1428, 800, 'Casual Dining', TRUE),
('Sri Punjabi Dhaba', 'BTM', 'Bangalore', 'North Indian', 3.3, 39, 400, 'Dhaba', TRUE),
('Arabian Mexico', 'Bannerghatta Road', 'Bangalore', 'Fast Food', 3.4, 43, 400, 'Quick Bites', TRUE),
('CakeZone', 'JP Nagar', 'Bangalore', 'Bakery', 3.7, 13, 200, 'Takeaway', TRUE),
('Fujian Express', 'JP Nagar', 'Bangalore', 'Chinese', 3.6, 34, 200, 'Quick Bites', TRUE),
('Indian Food', 'BTM', 'Bangalore', 'North Indian', 2.9, 345, 450, 'Takeaway', TRUE),
('Tandoori Paradise', 'BTM', 'Bangalore', 'North Indian', 3.5, 8, 600, 'Delivery', TRUE),
('Kolkata Kathi Rolls', 'JP Nagar', 'Bangalore', 'Rolls', 3.8, 23, 150, 'Quick Bites', TRUE),
('Adithya', 'JP Nagar', 'Bangalore', 'South Indian', 4.0, 332, 300, 'Quick Bites', TRUE),
('Cheesiano Pizza', 'JP Nagar', 'Bangalore', 'Pizza', 4.0, 199, 700, 'Quick Bites', TRUE),
('Polar Bear', 'BTM', 'Bangalore', 'Desserts', 3.9, 20, 300, 'Takeaway', TRUE),
('Nati Palace', 'JP Nagar', 'Bangalore', 'South Indian', 3.5, 11, 200, 'Quick Bites', TRUE),
('KFC', 'JP Nagar', 'Bangalore', 'Burger', 3.9, 437, 400, 'Quick Bites', TRUE),
('Dande''s Hyderabad Biryani', 'Bannerghatta Road', 'Bangalore', 'Biryani', 3.8, 207, 700, 'Casual Dining', TRUE),
('Onesta', 'JP Nagar', 'Bangalore', 'Pizza', 4.4, 4381, 600, 'Casual Dining', TRUE),
('Upahara Bhavan', 'Bannerghatta Road', 'Bangalore', 'South Indian', 3.8, 55, 300, 'Quick Bites', TRUE),
('Sher-E-Punjab', 'BTM', 'Bangalore', 'North Indian', 3.2, 19, 400, 'Quick Bites', TRUE),
('Shuddh Desi Khana', 'Bannerghatta Road', 'Bangalore', 'North Indian', 4.0, 597, 400, 'Quick Bites', TRUE),
('Karama Restaurant', 'JP Nagar', 'Bangalore', 'Arabian', 3.5, 16, 400, 'Takeaway', TRUE),
('Jaganath Hotel and Restaurant', 'JP Nagar', 'Bangalore', 'North Indian', 3.6, 35, 200, 'Quick Bites', TRUE),
('Five Star Chicken', 'Bannerghatta Road', 'Bangalore', 'Fast Food', 3.5, 9, 250, 'Quick Bites', TRUE),
('Sankranthi Veg Restaurant', 'BTM', 'Bangalore', 'South Indian', 3.0, 102, 600, 'Casual Dining', TRUE),
('Aramane Donne Biriyani', 'BTM', 'Bangalore', 'Biryani', 3.9, 189, 300, 'Quick Bites', TRUE),
('Cafe Potpourri', 'JP Nagar', 'Bangalore', 'Cafe', 3.7, 131, 400, 'Cafe', TRUE),
('Mani''s Dum Biryani', 'JP Nagar', 'Bangalore', 'Biryani', 4.2, 373, 750, 'Casual Dining', TRUE),
('Amontron', 'BTM', 'Bangalore', 'Bengali', 3.9, 435, 650, 'Casual Dining', TRUE),
('A M Biryani Hotel', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.3, 6, 300, 'Quick Bites', TRUE),
('Birinz', 'BTM', 'Bangalore', 'Biryani', 4.1, 292, 700, 'Casual Dining', TRUE),
('Just Shawarma', 'Bannerghatta Road', 'Bangalore', 'Arabian', 3.6, 137, 300, 'Quick Bites', TRUE),
('Hyderabadi Bawarchi', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.2, 133, 500, 'Casual Dining', TRUE),
('Fish Chain', 'JP Nagar', 'Bangalore', 'Seafood', 3.9, 37, 250, 'Takeaway', TRUE),
('Prasiddhi Food Corner', 'JP Nagar', 'Bangalore', 'Fast Food', 3.7, 170, 200, 'Quick Bites', TRUE),
('Biriyani Bhatti', 'BTM', 'Bangalore', 'Chinese', 3.7, 21, 400, 'Quick Bites', TRUE),
('Hyderabad Biryaani House', 'Bannerghatta Road', 'Bangalore', 'Biryani', 3.6, 794, 550, 'Casual Dining', TRUE),
('Galito''s', 'Bannerghatta Road', 'Bangalore', 'African', 4.6, 404, 1000, 'Casual Dining', TRUE),
('C. K. Mega Hot Food', 'BTM', 'Bangalore', 'Chinese', 3.9, 100, 600, 'Casual Dining', TRUE),
('Lassi Shop', 'JP Nagar', 'Bangalore', 'Beverages', 3.9, 38, 300, 'Beverage Shop', TRUE),
('Red Chilli Restaurant', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.2, 93, 350, 'Quick Bites', TRUE),
('RSS Donne Biryani', 'BTM', 'Bangalore', 'Biryani', 3.3, 58, 300, 'Quick Bites', TRUE),
('Rajdhani Thali Restaurant', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.9, 561, 900, 'Casual Dining', TRUE),
('PHEW (Play Hard Eat Wild)', 'BTM', 'Bangalore', 'Continental', 3.9, 486, 700, 'Cafe', TRUE),
('New Kabab Zone', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.6, 102, 500, 'Quick Bites', TRUE),
('Bawarchi Paradise', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.5, 89, 500, 'Quick Bites', TRUE),
('Shree Udupi Grand', 'Kanakapura Road', 'Bangalore', 'South Indian', 3.5, 17, 450, 'Casual Dining', TRUE),
('Chicken County Grand', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.9, 320, 650, 'Casual Dining', TRUE),
('Roll Over', 'JP Nagar', 'Bangalore', 'Desserts', 4.1, 237, 500, 'Dessert Parlor', TRUE),
('Darjeeling Momos & Fast Food Center', 'Bannerghatta Road', 'Bangalore', 'Fast Food', 3.8, 37, 250, 'Quick Bites', TRUE),
('Veruthe Oru Thattukada', 'BTM', 'Bangalore', 'Kerala', 3.7, 27, 400, 'Quick Bites', TRUE),
('Savoury - Sea Shell Restaurant', 'Bannerghatta Road', 'Bangalore', 'Arabian', 3.9, 1227, 900, 'Casual Dining', TRUE),
('Warm Oven', 'BTM', 'Bangalore', 'Bakery', 3.9, 32, 500, 'Bakery', TRUE),
('Firangi Bake', 'Bannerghatta Road', 'Bangalore', 'Mexican', 4.0, 95, 600, 'Delivery', TRUE),
('Zaitoon', 'JP Nagar', 'Bangalore', 'BBQ', 4.1, 1538, 1000, 'Casual Dining', TRUE),
('Kundana', 'Bannerghatta Road', 'Bangalore', 'Andhra', 3.7, 110, 800, 'Casual Dining', TRUE),
('Food Ka Masti', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.2, 45, 400, 'Delivery', TRUE),
('The Shawarma Shop', 'BTM', 'Bangalore', 'Arabian', 4.1, 381, 250, 'Quick Bites', TRUE),
('Momo Junction', 'Bannerghatta Road', 'Bangalore', 'Fast Food', 3.8, 87, 100, 'Takeaway', TRUE),
('Antilla Aromas', 'Bannerghatta Road', 'Bangalore', 'Desserts', 3.7, 18, 300, 'Dessert Parlor', TRUE),
('Faasos', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.9, 251, 500, 'Delivery', TRUE),
('Punjabi Food Corner', 'JP Nagar', 'Bangalore', 'North Indian', 3.0, 353, 400, 'Quick Bites', TRUE),
('Mealer.in', 'JP Nagar', 'Bangalore', 'North Indian', 4.0, 205, 450, 'Delivery', TRUE),
('Pathaan Sir', 'BTM', 'Bangalore', 'Fast Food', 3.9, 183, 250, 'Quick Bites', TRUE),
('Cold Stone Creamery', 'Bannerghatta Road', 'Bangalore', 'Ice Cream', 3.9, 99, 400, 'Dessert Parlor', TRUE),
('Hari Super Sandwich', 'BTM', 'Bangalore', 'Sandwich', 3.9, 13, 100, 'Quick Bites', TRUE),
('Amritsari Kulcha Land', 'JP Nagar', 'Bangalore', 'North Indian', 4.1, 260, 300, 'Quick Bites', TRUE),
('Chokha Chowka', 'BTM', 'Bangalore', 'North Indian', 3.9, 355, 400, 'Quick Bites', TRUE),
('Gorbandh', 'BTM', 'Bangalore', 'Fast Food', 4.1, 83, 400, 'Quick Bites', TRUE),
('Grills & Rolls', 'JP Nagar', 'Bangalore', 'North Indian', 2.5, 321, 400, 'Quick Bites', TRUE),
('Bathinda Junction', 'BTM', 'Bangalore', 'North Indian', 3.9, 362, 600, 'Casual Dining', TRUE),
('Stories', 'JP Nagar', 'Bangalore', 'American', 4.2, 2166, 1200, 'Pub', TRUE),
('New Gongura''s', 'BTM', 'Bangalore', 'Andhra', 3.7, 43, 550, 'Casual Dining', TRUE),
('Sagar Grand', 'Bannerghatta Road', 'Bangalore', 'South Indian', 3.8, 30, 300, 'Quick Bites', TRUE),
('Kanti Sweets', 'JP Nagar', 'Bangalore', 'Mithai', 4.0, 182, 400, 'Sweet Shop', TRUE),
('UBQ By Barbeque Nation', 'JP Nagar', 'Bangalore', 'North Indian', 3.4, 9, 450, 'Delivery', TRUE),
('Agarwal Food Service', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.8, 265, 400, 'Delivery', TRUE),
('Daniyal''s', 'BTM', 'Bangalore', 'North Indian', 3.1, 41, 800, 'Quick Bites', TRUE),
('Seasons', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.8, 500, 1000, 'Casual Dining', TRUE),
('Chef Delicacies', 'JP Nagar', 'Bangalore', 'Kebab', 3.1, 7, 400, 'Takeaway', TRUE),
('Chung Wah', 'Bannerghatta Road', 'Bangalore', 'Chinese', 4.0, 532, 800, 'Casual Dining', TRUE),
('Indiana Burgers', 'BTM', 'Bangalore', 'Burger', 3.4, 23, 300, 'Delivery', TRUE),
('Moksha', 'Kanakapura Road', 'Bangalore', 'Chinese', 3.6, 42, 1500, 'Casual Dining', TRUE),
('Marwa Restaurant', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.5, 551, 600, 'Casual Dining', TRUE),
('Chaatimes', 'JP Nagar', 'Bangalore', 'Street Food', 3.9, 100, 200, 'Quick Bites', TRUE),
('Shanghai Court', 'Bannerghatta Road', 'Bangalore', 'Chinese', 4.2, 421, 700, 'Casual Dining', TRUE),
('Akshaya Donne Biriyani', 'JP Nagar', 'Bangalore', 'Biryani', 3.1, 38, 300, 'Quick Bites', TRUE),
('Sweet Truth', 'Bannerghatta Road', 'Bangalore', 'Bakery', 3.7, 33, 500, 'Bakery', TRUE),
('Bhojohori Manna', 'JP Nagar', 'Bangalore', 'Bengali', 3.7, 662, 650, 'Casual Dining', TRUE),
('Richie Rich', 'JP Nagar', 'Bangalore', 'Desserts', 3.1, 14, 250, 'Takeaway', TRUE),
('Hunger Bee', 'Bannerghatta Road', 'Bangalore', 'Biryani', 3.8, 54, 500, 'Quick Bites', TRUE),
('Yum In My Tum', 'BTM', 'Bangalore', 'Chinese', 4.1, 92, 300, 'Quick Bites', TRUE),
('Maggi N Maggi House', 'Bannerghatta Road', 'Bangalore', 'Fast Food', 3.4, 22, 300, 'Takeaway', TRUE),
('Fresh Dinner', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.1, 105, 500, 'Takeaway', TRUE),
('B.M.W Bhookh Mitaane Wala', 'JP Nagar', 'Bangalore', 'North Indian', 3.5, 8, 500, 'Quick Bites', TRUE),
('Biryani Miya', 'JP Nagar', 'Bangalore', 'Biryani', 3.7, 36, 600, 'Delivery', TRUE),
('Krispy Kreme', 'Bannerghatta Road', 'Bangalore', 'Desserts', 3.7, 14, 300, 'Dessert Parlor', TRUE),
('Paani Kum Chai', 'JP Nagar', 'Bangalore', 'Beverages', 4.0, 23, 200, 'Beverage Shop', TRUE),
('Chulha Chauki Da Dhaba', 'JP Nagar', 'Bangalore', 'North Indian', 4.2, 2350, 800, 'Casual Dining', TRUE),
('SGS Non Veg - Gundu Pulav', 'Bannerghatta Road', 'Bangalore', 'Biryani', 3.9, 120, 300, 'Quick Bites', TRUE),
('Dreamcatcher', 'Bannerghatta Road', 'Bangalore', 'Cafe', 3.9, 49, 600, 'Cafe', TRUE),
('Magix''s Parattha Roll', 'BTM', 'Bangalore', 'Fast Food', 3.7, 184, 400, 'Quick Bites', TRUE),
('Elegant Dining', 'Bannerghatta Road', 'Bangalore', 'Biryani', 3.6, 225, 700, 'Casual Dining', TRUE),
('AlienSip', 'BTM', 'Bangalore', 'Juices', 3.6, 11, 200, 'Beverage Shop', TRUE),
('Waffle Head', 'BTM', 'Bangalore', 'Desserts', 4.0, 35, 300, 'Dessert Parlor', TRUE),
('Samruddhi Biryani', 'Bannerghatta Road', 'Bangalore', 'Biryani', 3.0, 45, 700, 'Delivery', TRUE),
('Ande Ka Funda', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.2, 56, 250, 'Quick Bites', TRUE),
('Basmati Delights', 'BTM', 'Bangalore', 'Biryani', 4.0, 869, 500, 'Delivery', TRUE),
('Charlee''s Chicken', 'Bannerghatta Road', 'Bangalore', 'Rolls', 3.2, 34, 300, 'Quick Bites', TRUE),
('Samosa Singh', 'JP Nagar', 'Bangalore', 'Street Food', 4.0, 153, 200, 'Quick Bites', TRUE),
('Cravings', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.7, 139, 400, 'Quick Bites', TRUE),
('Nagas', 'JP Nagar', 'Bangalore', 'Andhra', 3.1, 10, 300, 'Quick Bites', TRUE),
('Matka', 'Bannerghatta Road', 'Bangalore', 'Biryani', 3.7, 181, 500, 'Delivery', TRUE),
('Punjabi Swag', 'BTM', 'Bangalore', 'North Indian', 3.9, 669, 500, 'Casual Dining', TRUE),
('Taco Bell', 'Bannerghatta Road', 'Bangalore', 'Mexican', 3.7, 168, 600, 'Quick Bites', TRUE),
('Ambur Star Dum Biryani', 'Jayanagar', 'Bangalore', 'Biryani', 3.4, 17, 100, 'Quick Bites', TRUE),
('Mother''s Rasoi', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.8, 170, 250, 'Quick Bites', TRUE),
('Dosa Bazaar', 'JP Nagar', 'Bangalore', 'Street Food', 4.0, 112, 200, 'Quick Bites', TRUE),
('Babu Moshai', 'Bannerghatta Road', 'Bangalore', 'Fast Food', 3.0, 43, 500, 'Quick Bites', TRUE),
('The Bong Palate', 'BTM', 'Bangalore', 'Bengali', 3.8, 58, 300, 'Quick Bites', TRUE),
('Gowdru Mane Oota', 'JP Nagar', 'Bangalore', 'South Indian', 3.7, 80, 400, 'Quick Bites', TRUE),
('Banashankari Nati Style', 'JP Nagar', 'Bangalore', 'South Indian', 3.6, 8, 300, 'Quick Bites', TRUE),
('Upahara Darshini', 'Jayanagar', 'Bangalore', 'South Indian', 4.0, 167, 400, 'Quick Bites', TRUE),
('Chandrima''s Kitchen', 'Bannerghatta Road', 'Bangalore', 'Bengali', 3.7, 38, 400, 'Takeaway', TRUE),
('Keventers', 'Bannerghatta Road', 'Bangalore', 'Desserts', 3.8, 29, 400, 'Beverage Shop', TRUE),
('Bikaner Jn', 'JP Nagar', 'Bangalore', 'Rajasthani', 3.9, 85, 300, 'Quick Bites', TRUE),
('Crunch Pizzas', 'BTM', 'Bangalore', 'Italian', 2.6, 473, 600, 'Quick Bites', TRUE),
('Lassi Berg', 'BTM', 'Bangalore', 'Juices', 3.4, 13, 100, 'Takeaway', TRUE),
('Kakal-Kai Ruchi', 'JP Nagar', 'Bangalore', 'North Indian', 3.7, 217, 500, 'Casual Dining', TRUE),
('Manchu Cafe', 'BTM', 'Bangalore', 'Chinese', 3.8, 21, 300, 'Quick Bites', TRUE),
('Calorie Express', 'BTM', 'Bangalore', 'Healthy Food', 3.6, 192, 450, 'Delivery', TRUE),
('BANGALORE BOX', 'BTM', 'Bangalore', 'Asian', 4.2, 611, 1500, 'Casual Dining', TRUE),
('Yummy Momos', 'Bannerghatta Road', 'Bangalore', 'Momos', 3.6, 44, 200, 'Kiosk', TRUE),
('Hotel Khaaja', 'Bannerghatta Road', 'Bangalore', 'Biryani', 3.1, 68, 250, 'Quick Bites', TRUE),
('The Gujarat Express', 'Bannerghatta Road', 'Bangalore', 'Street Food', 3.1, 16, 250, 'Quick Bites', TRUE),
('Ovenstory Pizza', 'Bannerghatta Road', 'Bangalore', 'Pizza', 4.0, 166, 750, 'Delivery', TRUE),
('Slate Cafe', 'JP Nagar', 'Bangalore', 'Cafe', 4.1, 46, 600, 'Cafe', TRUE),
('Vishal Foods', 'Bannerghatta Road', 'Bangalore', 'Chinese', 3.3, 57, 250, 'Quick Bites', TRUE),
('Lassi Darbar', 'BTM', 'Bangalore', 'Ice Cream', 3.5, 11, 200, 'Beverage Shop', TRUE),
('Chavadi', 'Bannerghatta Road', 'Bangalore', 'Continental', 4.4, 2233, 1200, 'Casual Dining', TRUE),
('Nanna Munna Paratha House', 'BTM', 'Bangalore', 'North Indian', 4.0, 107, 300, 'Quick Bites', TRUE),
('Cucumber Town', 'BTM', 'Bangalore', 'Kerala', 4.2, 306, 600, 'Delivery', TRUE),
('Sri Sai 99 Variety Dosa', 'Bannerghatta Road', 'Bangalore', 'South Indian', 3.7, 32, 300, 'Quick Bites', TRUE),
('Oye Amritsar', 'JP Nagar', 'Bangalore', 'North Indian', 3.8, 756, 1000, 'Casual Dining', TRUE),
('Kolkata Famous Kati Roll', 'JP Nagar', 'Bangalore', 'Rolls', 3.5, 11, 200, 'Quick Bites', TRUE),
('Nellore Ruchulu', 'Bannerghatta Road', 'Bangalore', 'North Indian', 3.7, 30, 800, 'Casual Dining', TRUE),
('Brewsky', 'JP Nagar', 'Bangalore', 'Continental', 4.4, 4309, 1600, 'Microbrewery', TRUE),
('Chefeana', 'Bannerghatta Road', 'Bangalore', 'North Indian', 4.0, 212, 400, 'Quick Bites', TRUE),
('Bangaliana', 'Bannerghatta Road', 'Bangalore', 'Bengali', 2.9, 153, 600, 'Quick Bites', TRUE),
('Gud Dhani', 'BTM', 'Bangalore', 'Rajasthani', 4.0, 827, 500, 'Casual Dining', TRUE);
